### ISSUE TITLE
can't change ringtone on Pixel 3XL

### ISSUE THREAD

**Issue by renlord** [GrapheneOS/os_issue_tracker#147]
when trying to change ringtone from "unknown" to something else.
OS crashes as activity stuck in loop. Require hard reboot to get out of loop.

screentshot at settings->sound: https://imgur.com/a/lSiQHTq

logcat logs when tapped on settings->sound->phone ringtone:

```
10-25 20:58:06.835  1337  1406 I ActivityManager: Start proc 9394:android.process.media/u0a15 for activity {com.android.providers.media/com.android.providers.media.RingtonePickerActivity}
10-25 20:58:06.839  9394  9394 E d.process.medi: Not starting debugger since process cannot load the jdwp agent.
10-25 20:58:06.956  9394  9394 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 10015 <<<<<<
10-25 20:58:06.958  9394  9394 W d.process.media: type=1400 audit(0.0:19348): avc: denied { read } for name="u:object_r:device_config_runtime_native_boot_prop:s0" dev="tmpfs" ino=23054 scontext=u:r:mediaprovider:s0:c512,c768 tcontext=u:object_r:device_config_runtime_native_boot_prop:s0 tclass=file permissive=0
10-25 20:58:06.960  9394  9394 E libc    : Access denied finding property "persist.device_config.runtime_native_boot.enable_apex_image"
10-25 20:58:06.960  9394  9394 I AndroidRuntime: Using default boot image
10-25 20:58:06.960  9394  9394 E libc    : Access denied finding property "persist.device_config.runtime_native_boot.disable_lock_profiling"
10-25 20:58:06.961  9394  9394 I AndroidRuntime: Leaving lock profiling enabled
10-25 20:58:06.961  9394  9394 E libc    : Access denied finding property "persist.device_config.runtime_native_boot.enable_generational_cc"
10-25 20:58:06.961  9394  9394 W d.process.media: type=1400 audit(0.0:19351): avc: denied { lock } for path="/system/framework/arm64/boot.art" dev="dm-3" ino=1617 scontext=u:r:mediaprovider:s0:c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0
10-25 20:58:07.055  9394  9394 D ICU     : Time zone APEX file found: /apex/com.android.tzdata/etc/icu/icu_tzdata.dat
10-25 20:58:07.081  9394  9394 W android.process.media: JNI RegisterNativeMethods: attempt to register 0 native methods for android.media.AudioAttributes
10-25 20:58:07.085  9394  9394 D AndroidRuntime: Calling main entry com.android.internal.os.ExecInit
10-25 20:58:07.085  9394  9394 D Zygote  : begin preload
10-25 20:58:07.086  9394  9394 I Zygote  : Calling ZygoteHooks.beginPreload()
10-25 20:58:07.086  9394  9394 I Zygote  : Preloading shared libraries...
10-25 20:58:07.098  1337  1337 V SettingsProvider: Notifying for 0: content://settings/system/screen_brightness
10-25 20:58:07.165  9394  9394 I Zygote  : Called ZygoteHooks.endPreload()
10-25 20:58:07.177  9394  9394 I Zygote  : Installed AndroidKeyStoreProvider in 12ms.
10-25 20:58:07.177  9394  9394 D Zygote  : end preload
10-25 20:58:07.212  9394  9394 W asset   : unable to execute idmap2: Permission denied
10-25 20:58:07.212  9394  9394 W AssetManager: 'idmap2 --scan' failed: no static="true" overlays targeting "android" will be loaded
10-25 20:58:07.257  9394  9426 D libEGL  : loaded /vendor/lib64/egl/libEGL_adreno.so
10-25 20:58:07.264  9394  9426 D libEGL  : loaded /vendor/lib64/egl/libGLESv1_CM_adreno.so
10-25 20:58:07.268  9394  9426 D libEGL  : loaded /vendor/lib64/egl/libGLESv2_adreno.so
10-25 20:58:07.281   673   673 E SELinux : avc:  denied  { find } for service=gpu pid=9394 uid=10015 scontext=u:r:mediaprovider:s0:c512,c768 tcontext=u:object_r:gpu_service:s0 tclass=service_manager permissive=0
10-25 20:58:07.281  9394  9426 E GraphicsEnv: Failed to get gpu service
10-25 20:58:07.293  9394  9394 D AndroidRuntime: Shutting down VM
10-25 20:58:07.293  9394  9394 E AndroidRuntime: FATAL EXCEPTION: main
10-25 20:58:07.293  9394  9394 E AndroidRuntime: Process: android.process.media, PID: 9394
10-25 20:58:07.293  9394  9394 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.providers.media/com.android.providers.media.RingtonePickerActivity}: java.lang.NumberFormatException: For input string: "ringtone"
10-25 20:58:07.293  9394  9394 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
10-25 20:58:07.293  9394  9394 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
10-25 20:58:07.293  9394  9394 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
10-25 20:58:07.293  9394  9394 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
10-25 20:58:07.293  9394  9394 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
10-25 20:58:07.293  9394  9394 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
10-25 20:58:07.293  9394  9394 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
10-25 20:58:07.293  9394  9394 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
10-25 20:58:07.293  9394  9394 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
10-25 20:58:07.293  9394  9394 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-25 20:58:07.293  9394  9394 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
10-25 20:58:07.293  9394  9394 E AndroidRuntime: 	at com.android.internal.os.ExecInit.main(ExecInit.java:43)
10-25 20:58:07.293  9394  9394 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
10-25 20:58:07.293  9394  9394 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:338)
10-25 20:58:07.293  9394  9394 E AndroidRuntime: Caused by: java.lang.NumberFormatException: For input string: "ringtone"
10-25 20:58:07.293  9394  9394 E AndroidRuntime: 	at java.lang.Long.parseLong(Long.java:594)
10-25 20:58:07.293  9394  9394 E AndroidRuntime: 	at java.lang.Long.parseLong(Long.java:636)
10-25 20:58:07.293  9394  9394 E AndroidRuntime: 	at android.content.ContentUris.parseId(ContentUris.java:89)
10-25 20:58:07.293  9394  9394 E AndroidRuntime: 	at android.media.RingtoneManager.getRingtonePosition(RingtoneManager.java:513)
10-25 20:58:07.293  9394  9394 E AndroidRuntime: 	at com.android.providers.media.RingtonePickerActivity.onPrepareListView(RingtonePickerActivity.java:369)
10-25 20:58:07.293  9394  9394 E AndroidRuntime: 	at com.android.internal.app.AlertController$AlertParams.createListView(AlertController.java:1209)
10-25 20:58:07.293  9394  9394 E AndroidRuntime: 	at com.android.internal.app.AlertController$AlertParams.apply(AlertController.java:1119)
10-25 20:58:07.293  9394  9394 E AndroidRuntime: 	at com.android.internal.app.AlertController.installContent(AlertController.java:264)
10-25 20:58:07.293  9394  9394 E AndroidRuntime: 	at com.android.internal.app.AlertActivity.setupAlert(AlertActivity.java:98)
10-25 20:58:07.293  9394  9394 E AndroidRuntime: 	at com.android.providers.media.RingtonePickerActivity.onCreate(RingtonePickerActivity.java:262)
10-25 20:58:07.293  9394  9394 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7802)
10-25 20:58:07.293  9394  9394 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7791)
10-25 20:58:07.293  9394  9394 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
10-25 20:58:07.293  9394  9394 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
10-25 20:58:07.293  9394  9394 E AndroidRuntime: 	... 13 more
10-25 20:58:07.293  9394  9394 E AndroidRuntime: Error reporting crash
10-25 20:58:07.293  9394  9394 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
10-25 20:58:07.293  9394  9394 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
10-25 20:58:07.293  9394  9394 E AndroidRuntime: 	at android.os.BinderProxy.transact(BinderProxy.java:510)
10-25 20:58:07.293  9394  9394 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.handleApplicationCrash(IActivityManager.java:4653)
10-25 20:58:07.293  9394  9394 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:145)
10-25 20:58:07.293  9394  9394 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
10-25 20:58:07.293  9394  9394 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
10-25 20:58:07.293  9394  9394 E AndroidRuntime: 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2187)
10-25 20:58:07.294  9394  9394 I Process : Sending signal. PID: 9394 SIG: 9
10-25 20:58:07.325  1337  2374 I ActivityManager: Process android.process.media (pid 9394) has died: fore TOP
10-25 20:58:07.325  1337  1407 I libprocessgroup: Successfully killed process cgroup uid 10015 pid 9394 in 0ms
10-25 20:58:07.326   863   863 I Zygote  : Process 9394 exited due to signal 9 (Killed)
10-25 20:58:07.352   863   863 D Zygote  : Forked child process 9427
10-25 20:58:07.357  1337  1406 I ActivityManager: Start proc 9427:android.process.media/u0a15 for activity {com.android.providers.media/com.android.providers.media.RingtonePickerActivity}
10-25 20:58:07.366  9427  9427 E d.process.medi: Not starting debugger since process cannot load the jdwp agent.
10-25 20:58:07.486  9427  9427 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 10015 <<<<<<
10-25 20:58:07.490  9427  9427 E libc    : Access denied finding property "persist.device_config.runtime_native_boot.enable_apex_image"
10-25 20:58:07.490  9427  9427 I AndroidRuntime: Using default boot image
10-25 20:58:07.490  9427  9427 E libc    : Access denied finding property "persist.device_config.runtime_native_boot.disable_lock_profiling"
10-25 20:58:07.490  9427  9427 I AndroidRuntime: Leaving lock profiling enabled
10-25 20:58:07.490  9427  9427 E libc    : Access denied finding property "persist.device_config.runtime_native_boot.enable_generational_cc"
10-25 20:58:07.589  9427  9427 D ICU     : Time zone APEX file found: /apex/com.android.tzdata/etc/icu/icu_tzdata.dat
10-25 20:58:07.614  9427  9427 W android.process.media: JNI RegisterNativeMethods: attempt to register 0 native methods for android.media.AudioAttributes
10-25 20:58:07.618  9427  9427 D AndroidRuntime: Calling main entry com.android.internal.os.ExecInit
10-25 20:58:07.618  9427  9427 D Zygote  : begin preload
10-25 20:58:07.619  9427  9427 I Zygote  : Calling ZygoteHooks.beginPreload()
10-25 20:58:07.619  9427  9427 I Zygote  : Preloading shared libraries...
10-25 20:58:07.698  9427  9427 I Zygote  : Called ZygoteHooks.endPreload()
10-25 20:58:07.711  9427  9427 I Zygote  : Installed AndroidKeyStoreProvider in 13ms.
10-25 20:58:07.711  9427  9427 D Zygote  : end preload
10-25 20:58:07.748  9427  9427 W asset   : unable to execute idmap2: Permission denied
10-25 20:58:07.748  9427  9427 W AssetManager: 'idmap2 --scan' failed: no static="true" overlays targeting "android" will be loaded
10-25 20:58:07.744  9427  9427 W d.process.media: type=1400 audit(0.0:19377): avc: denied { execute } for name="idmap2" dev="dm-3" ino=590 scontext=u:r:mediaprovider:s0:c512,c768 tcontext=u:object_r:idmap_exec:s0 tclass=file permissive=0
10-25 20:58:07.795  9427  9459 D libEGL  : loaded /vendor/lib64/egl/libEGL_adreno.so
10-25 20:58:07.803  9427  9459 D libEGL  : loaded /vendor/lib64/egl/libGLESv1_CM_adreno.so
10-25 20:58:07.808  9427  9459 D libEGL  : loaded /vendor/lib64/egl/libGLESv2_adreno.so
10-25 20:58:07.820   673   673 E SELinux : avc:  denied  { find } for service=gpu pid=9427 uid=10015 scontext=u:r:mediaprovider:s0:c512,c768 tcontext=u:object_r:gpu_service:s0 tclass=service_manager permissive=0
10-25 20:58:07.820  9427  9459 E GraphicsEnv: Failed to get gpu service
10-25 20:58:07.831  9427  9427 D AndroidRuntime: Shutting down VM
10-25 20:58:07.832  9427  9427 E AndroidRuntime: FATAL EXCEPTION: main
10-25 20:58:07.832  9427  9427 E AndroidRuntime: Process: android.process.media, PID: 9427
10-25 20:58:07.832  9427  9427 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.providers.media/com.android.providers.media.RingtonePickerActivity}: java.lang.NumberFormatException: For input string: "ringtone"
10-25 20:58:07.832  9427  9427 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
10-25 20:58:07.832  9427  9427 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
10-25 20:58:07.832  9427  9427 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
10-25 20:58:07.832  9427  9427 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
10-25 20:58:07.832  9427  9427 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
10-25 20:58:07.832  9427  9427 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
10-25 20:58:07.832  9427  9427 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
10-25 20:58:07.832  9427  9427 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
10-25 20:58:07.832  9427  9427 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
10-25 20:58:07.832  9427  9427 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-25 20:58:07.832  9427  9427 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
10-25 20:58:07.832  9427  9427 E AndroidRuntime: 	at com.android.internal.os.ExecInit.main(ExecInit.java:43)
10-25 20:58:07.832  9427  9427 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
10-25 20:58:07.832  9427  9427 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:338)
10-25 20:58:07.832  9427  9427 E AndroidRuntime: Caused by: java.lang.NumberFormatException: For input string: "ringtone"
10-25 20:58:07.832  9427  9427 E AndroidRuntime: 	at java.lang.Long.parseLong(Long.java:594)
10-25 20:58:07.832  9427  9427 E AndroidRuntime: 	at java.lang.Long.parseLong(Long.java:636)
10-25 20:58:07.832  9427  9427 E AndroidRuntime: 	at android.content.ContentUris.parseId(ContentUris.java:89)
10-25 20:58:07.832  9427  9427 E AndroidRuntime: 	at android.media.RingtoneManager.getRingtonePosition(RingtoneManager.java:513)
10-25 20:58:07.832  9427  9427 E AndroidRuntime: 	at com.android.providers.media.RingtonePickerActivity.onPrepareListView(RingtonePickerActivity.java:369)
10-25 20:58:07.832  9427  9427 E AndroidRuntime: 	at com.android.internal.app.AlertController$AlertParams.createListView(AlertController.java:1209)
10-25 20:58:07.832  9427  9427 E AndroidRuntime: 	at com.android.internal.app.AlertController$AlertParams.apply(AlertController.java:1119)
10-25 20:58:07.832  9427  9427 E AndroidRuntime: 	at com.android.internal.app.AlertController.installContent(AlertController.java:264)
10-25 20:58:07.832  9427  9427 E AndroidRuntime: 	at com.android.internal.app.AlertActivity.setupAlert(AlertActivity.java:98)
10-25 20:58:07.832  9427  9427 E AndroidRuntime: 	at com.android.providers.media.RingtonePickerActivity.onCreate(RingtonePickerActivity.java:262)
10-25 20:58:07.832  9427  9427 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7802)
10-25 20:58:07.832  9427  9427 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7791)
10-25 20:58:07.832  9427  9427 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
10-25 20:58:07.832  9427  9427 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
10-25 20:58:07.832  9427  9427 E AndroidRuntime: 	... 13 more
10-25 20:58:07.832  9427  9427 E AndroidRuntime: Error reporting crash
10-25 20:58:07.832  9427  9427 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
10-25 20:58:07.832  9427  9427 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
10-25 20:58:07.832  9427  9427 E AndroidRuntime: 	at android.os.BinderProxy.transact(BinderProxy.java:510)
10-25 20:58:07.832  9427  9427 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.handleApplicationCrash(IActivityManager.java:4653)
10-25 20:58:07.832  9427  9427 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:145)
10-25 20:58:07.832  9427  9427 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
10-25 20:58:07.832  9427  9427 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
10-25 20:58:07.832  9427  9427 E AndroidRuntime: 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2187)
10-25 20:58:07.832  9427  9427 I Process : Sending signal. PID: 9427 SIG: 9
10-25 20:58:07.877  1337 10385 I ActivityManager: Process android.process.media (pid 9427) has died: fore TOP
10-25 20:58:07.878  1337  1407 I libprocessgroup: Successfully killed process cgroup uid 10015 pid 9427 in 0ms
10-25 20:58:07.878   863   863 I Zygote  : Process 9427 exited due to signal 9 (Killed)
10-25 20:58:07.893   863   863 D Zygote  : Forked child process 9460
10-25 20:58:07.895  1337  1406 I ActivityManager: Start proc 9460:android.process.media/u0a15 for activity {com.android.providers.media/com.android.providers.media.RingtonePickerActivity}
10-25 20:58:07.924  9460  9460 E d.process.medi: Not starting debugger since process cannot load the jdwp agent.
10-25 20:58:08.049  9460  9460 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 10015 <<<<<<
10-25 20:58:08.051  9460  9460 W d.process.media: type=1400 audit(0.0:19378): avc: denied { read } for name="u:object_r:device_config_runtime_native_boot_prop:s0" dev="tmpfs" ino=23054 scontext=u:r:mediaprovider:s0:c512,c768 tcontext=u:object_r:device_config_runtime_native_boot_prop:s0 tclass=file permissive=0
10-25 20:58:08.053  9460  9460 E libc    : Access denied finding property "persist.device_config.runtime_native_boot.enable_apex_image"
10-25 20:58:08.053  9460  9460 I AndroidRuntime: Using default boot image
10-25 20:58:08.053  9460  9460 E libc    : Access denied finding property "persist.device_config.runtime_native_boot.disable_lock_profiling"
10-25 20:58:08.053  9460  9460 I AndroidRuntime: Leaving lock profiling enabled
10-25 20:58:08.053  9460  9460 E libc    : Access denied finding property "persist.device_config.runtime_native_boot.enable_generational_cc"
10-25 20:58:08.054  9460  9460 W d.process.media: type=1400 audit(0.0:19381): avc: denied { lock } for path="/system/framework/arm64/boot.art" dev="dm-3" ino=1617 scontext=u:r:mediaprovider:s0:c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0
```

**Comment by renlord** [comment]
looks like this issue in upstream: https://issuetracker.google.com/issues/139935440

**Comment by renlord** [comment]
To reproduce, go to settings->apps->reset app preferences.

Phone ringtone and Default notification sound will show "unknown"

**Comment by renlord** [comment]
To remedy, go to apps->MediaStorage and clear storage & cache. Also, reset app preferences. Then reboot.
