### ISSUE TITLE
GMS Crash

### ISSUE THREAD

**Issue by Klejdi-Bozho** [GrapheneOS/os_issue_tracker#2026]
```
type: crash
osVersion: google/raven/raven:13/TQ1A.230205.002/2023030400:user/release-keys
package: com.google.android.gms:230413044
process: com.google.android.gms.ui
processUptime: 2642530 + 232 ms
GmsCompatConfig version: 37

java.lang.SecurityException: Bad package name: zombie.survival.craft.z
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3021)
	at android.os.Parcel.createException(Parcel.java:3005)
	at android.os.Parcel.readException(Parcel.java:2981)
	at android.os.Parcel.readException(Parcel.java:2923)
	at aabw.gj(:com.google.android.gms@230413044@23.04.13 (190400-505809224):5)
	at aaac.y(:com.google.android.gms@230413044@23.04.13 (190400-505809224):11)
	at zzz.a(:com.google.android.gms@230413044@23.04.13 (190400-505809224):1)
	at aaab.d(:com.google.android.gms@230413044@23.04.13 (190400-505809224):0)
	at zzr.a(:com.google.android.gms@230413044@23.04.13 (190400-505809224):2)
	at zzu.handleMessage(:com.google.android.gms@230413044@23.04.13 (190400-505809224):23)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at atit.lE(:com.google.android.gms@230413044@23.04.13 (190400-505809224):0)
	at atit.dispatchMessage(:com.google.android.gms@230413044@23.04.13 (190400-505809224):13)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7879)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
	Suppressed: czjc: 
		at tk_trace.MainThreadWork(Unknown Source:0)
		at tk_trace.Missing root trace(Unknown Source:0)

```

**Comment by thestinger** [comment]
cc @muhomorr

**Comment by muhomorr** [comment]
This is likely an upstream bug. Try updating Play services to the latest version through Play Store.
