### ISSUE TITLE
system_server crash on Pixel 6a - Everything seems functional tho... 

### ISSUE THREAD

**Issue by thereforego** [GrapheneOS/os_issue_tracker#2755]
Crash happened after ending a sub profile session and connecting to a Bluetooth speaker on Owner profile.

```
type: crash
Process: unknown
Build: google/bluejay/bluejay:14/UP1A.231105.003/2023112900:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.resolveTypeIfNeeded(android.content.ContentResolver)' on a null object reference
	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:550)
	at android.app.PendingIntent.getActivity(PendingIntent.java:537)
	at android.app.PendingIntent.getActivity(PendingIntent.java:501)
	at org.torproject.android.service.OrbotService.showToolbarNotification(OrbotService.java:178)
	at org.torproject.android.service.OrbotService.showBandwidthNotification(OrbotService.java:1104)
	at org.torproject.android.service.OrbotRawEventListener.handleBandwidth(OrbotRawEventListener.java:83)
	at org.torproject.android.service.OrbotRawEventListener.onEvent(OrbotRawEventListener.java:43)
	at net.freehaven.tor.control.TorControlConnection.handleEvent(TorControlConnection.java:240)
	at net.freehaven.tor.control.TorControlConnection.react(TorControlConnection.java:382)
	at net.freehaven.tor.control.TorControlConnection$ControlParseThread.run(TorControlConnection.java:352)

```

**Comment by raghu-1136** [comment]
Happened to me today

**Comment by elvisisvan** [comment]
eyyo same device same build version, but i got a different crash though (adbd crash)

**Comment by thestinger** [comment]
@thereforego Do you still have an issue with the [2023120701](https://grapheneos.org/releases#2023120701) release?

**Comment by thestinger** [comment]
Please reopen if the crash still occurs after updating.
