### ISSUE TITLE
system_server crash

### ISSUE THREAD

**Issue by ellias-dev** [GrapheneOS/os_issue_tracker#2761]
Happens when end a secondary profile session and login to the Owner, as well as when restart the phone.

Report:
```
type: crash
Process: unknown
Build: google/oriole/oriole:14/UP1A.231105.003/2023112900:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.resolveTypeIfNeeded(android.content.ContentResolver)' on a null object reference
	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:550)
	at android.app.PendingIntent.getActivity(PendingIntent.java:537)
	at android.app.PendingIntent.getActivity(PendingIntent.java:501)
	at org.torproject.android.service.OrbotService.showToolbarNotification(OrbotService.java:188)
	at org.torproject.android.service.OrbotService.showBandwidthNotification(OrbotService.java:1256)
	at org.torproject.android.service.OrbotRawEventListener.handleBandwidth(OrbotRawEventListener.java:83)
	at org.torproject.android.service.OrbotRawEventListener.onEvent(OrbotRawEventListener.java:42)
	at net.freehaven.tor.control.TorControlConnection.handleEvent(TorControlConnection.java:240)
	at net.freehaven.tor.control.TorControlConnection.react(TorControlConnection.java:382)
	at net.freehaven.tor.control.TorControlConnection$ControlParseThread.run(TorControlConnection.java:352)

```

**Comment by muhomorr** [comment]
This doesn't look like a system_server crash. Was it reported as a system_server crash by the OS?

**Comment by ellias-dev** [comment]
![Screenshot_20231204-145443.png](https://github.com/GrapheneOS/os-issue-tracker/assets/96002710/11fdab29-ae09-4987-9198-f3e5886b9b53)

**Comment by thestinger** [comment]
Please reopen if it still happens on the 2023120701 release.
