### ISSUE TITLE
crash: com.google.android.gms ACROSS_USERS

### ISSUE THREAD

**Issue by tmplt** [GrapheneOS/os_issue_tracker#2844]
Below crash occurs every 10 minutes. Apps with hard depend (e.g. Spotify) crash during launch.

```
type: crash
osVersion: google/lynx/lynx:14/UP1A.231005.007/2023102300:user/release-keys
package: com.google.android.gms:234523038
process: com.google.android.gms.persistent
processUptime: 1314 + 436 ms
installer: com.android.vending
GmsCompatConfig version: 87

java.lang.SecurityException: Permission Denial: broadcast from com.google.android.gms asks to run as user -1 but is calling from uid u0a126; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3066)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5778)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1513)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1480)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:607)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:607)
	at awci.sendBroadcastAsUser(:com.google.android.gms@234523038@23.45.23 (190400-587848529):6)
	at cwgv.a(:com.google.android.gms@234523038@23.45.23 (190400-587848529):38)
	at cwgz.g(:com.google.android.gms@234523038@23.45.23 (190400-587848529):723)
	at cwgw.c(:com.google.android.gms@234523038@23.45.23 (190400-587848529):7)
	at cwgw.d(:com.google.android.gms@234523038@23.45.23 (190400-587848529):10)
	at cwhi.f(:com.google.android.gms@234523038@23.45.23 (190400-587848529):38)
	at bfsm.ff(:com.google.android.gms@234523038@23.45.23 (190400-587848529):1)
	at bfsx.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):100)
	at dvwy.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):13)
	at ajng.c(:com.google.android.gms@234523038@23.45.23 (190400-587848529):50)
	at ajng.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at ajsl.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: dvxr: 
		at tk_trace.326-singleuserapi.RetrieveGlobalState(Unknown Source:0)
		at tk_trace.time-TrustedTimeAllUserChimeraService-IGmsServiceBroker_45(Unknown Source:0)
		at tk_trace.thunderbird-EmergencyPersistentChimeraService_onCreate(Unknown Source:0)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.UserController.handleIncomingUser(UserController.java:2457)
	at com.android.server.am.ActivityManagerService.broadcastIntentLockedTraced(ActivityManagerService.java:14521)
	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:14431)
	at com.android.server.am.ActivityManagerService.broadcastIntentWithFeature(ActivityManagerService.java:15397)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2661)


```

**Comment by tmplt** [comment]
Indeed, no issue on UQ1A.231205.015.2023120800. For unknown reasons updates were not queued. I had to unset the charging and battery level conditions for the update to queue, even if conditions have certainly been met during the last two months.

**Comment by tmplt** [comment]
That does ring a bell. Thanks for the support!
