### ISSUE TITLE
Prompted for PIN when switching profiles when biometric available

### ISSUE THREAD

**Issue by doma9on** [GrapheneOS/os_issue_tracker#2847]
When switching profiles, I am immediately prompted to enter my PIN, as the keypad appears straight away rather than seeing the small icon to unlock with biometric/PIN. This may be related to [this issue](https://github.com/GrapheneOS/os-issue-tracker/issues/1611), however when I swipe down to close the keypad, biometric is sometimes available. It has been happening since QPR1 update of Android 14.

**Comment by Linentio** [comment]
I have the exact same behavior on my Pixel 7a and I confirm that it started happening after the Android 14 QPR1 update (2023120700 release). This issue occurs every time I switch between profiles.

Also, I haven't been able to find the steps to reproduce this issue so far but from time to time, right after switching profiles, I get a weird screen layout where I see at the same time the keypad of the PIN unlock with a transparent background and the lock screen, sometimes with the Quick Settings menu open, with the fingerprint unlock icon visible.
I'll add more information here if I manage to find a pattern to reproduce this problem.

**Comment by okpersonvern** [comment]
This exact behavior occurs on stock PixelOS as well. Including the bug that Linentio mentioned (fingerprint showing above the PIN input). 

Tested on:
PixelOS build UQ1A.231205.015
Device model 6a

**Comment by thestinger** [comment]
Thanks for checking if it occurs there. That means we can try to backport a patch.

**Comment by shinobinakamoto** [comment]
I have this on the 8 Pro.

**Comment by FID02** [comment]
Google seems to finally having fixed this in Android 14 QPR2: when switching between profiles that have fingerprint unlock configured, the fingerprint unlock option is displayed without delay.

Pixel 8. GrapheneOS 2024030700

**Comment by yuriymacdev** [comment]
It does work better, but still under some conditions for some of the profiles fingerprint gets disabled after switching profiles. Once fingerprint is deleted and re-added, it starts working again for those profiles (until those conditions arise again).

**Comment by io43** [comment]
for me it just started like 2 days ago when i update to latest version

**Comment by io43** [comment]
i had a bug when switching profile at about the same time that i noticed the pin thing, not sure if it help

```
type: crash
osVersion: google/shiba/shiba:14/AP1A.240405.002/2024040300:user/release-keys
package: com.android.systemui:34
process: com.android.systemui
processUptime: 8272293 + 504 ms

java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at com.android.systemui.settings.UserTrackerImpl.getUserInfo(go/retraceme ff6c91cbd2fa4e96aaf7beee3e24db29d9dd75c665873da3e0eba9fd165e36f6:34)
	at com.android.systemui.user.data.repository.UserRepositoryImpl$selectedUser$1$1.invokeSuspend$send(go/retraceme ff6c91cbd2fa4e96aaf7beee3e24db29d9dd75c665873da3e0eba9fd165e36f6:9)
	at com.android.systemui.user.data.repository.UserRepositoryImpl$selectedUser$1$1$callback$1.onProfilesChanged(go/retraceme ff6c91cbd2fa4e96aaf7beee3e24db29d9dd75c665873da3e0eba9fd165e36f6:11)
	at com.android.systemui.settings.UserTrackerImpl$handleProfilesChanged$$inlined$notifySubscribers$1.run(go/retraceme ff6c91cbd2fa4e96aaf7beee3e24db29d9dd75c665873da3e0eba9fd165e36f6:20)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8532)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
```

**Comment by FID02** [comment]
> for me it just started to happen 100% of the time since i updated to 2024040300, i tried to reboot but it wont help when switching to a running secondary profile it show pin instead of fingerprint but fingerprint is available if you cancel the pin prompt with back

Reproducible on Pixel 8.
This exact behaviour occurs on stock PixelOS as well (Pixel 6a), on the April patch release AP1A.240405.002
