### ISSUE TITLE
NFC tile seems to be unavailable on Android 11

### ISSUE THREAD

**Issue by inthewaves** [GrapheneOS/os_issue_tracker#285]
On Pixel 3a, 11 branch

Getting this error in the logcat
```
NFC     : could not retrieve NFC service
```
Logged from here https://github.com/GrapheneOS/platform_frameworks_base/blob/11/core/java/android/nfc/NfcAdapter.java#L606

This exception makes the NfcAdapter set `mAdapter` to null: https://github.com/GrapheneOS/platform_frameworks_base/blob/11/core/java/android/nfc/NfcManager.java#L60

Putting a `Log.e` with the stacktrace in that NfcManager constructor reveals:

```
09-10 11:16:33.363  1988  2190 E NFC     : could not retrieve NFC service
09-10 11:16:33.363  1988  2190 E NfcManager: NfcManager constructor: error null
09-10 11:16:33.363  1988  2190 E NfcManager: java.lang.UnsupportedOperationException
09-10 11:16:33.363  1988  2190 E NfcManager: 	at android.nfc.NfcAdapter.getNfcAdapter(NfcAdapter.java:607)
09-10 11:16:33.363  1988  2190 E NfcManager: 	at android.nfc.NfcManager.<init>(NfcManager.java:59)
09-10 11:16:33.363  1988  2190 E NfcManager: 	at android.app.SystemServiceRegistry$25.createService(SystemServiceRegistry.java:466)
09-10 11:16:33.363  1988  2190 E NfcManager: 	at android.app.SystemServiceRegistry$25.createService(SystemServiceRegistry.java:463)
09-10 11:16:33.363  1988  2190 E NfcManager: 	at android.app.SystemServiceRegistry$CachedServiceFetcher.getService(SystemServiceRegistry.java:1702)
09-10 11:16:33.363  1988  2190 E NfcManager: 	at android.app.SystemServiceRegistry.getSystemService(SystemServiceRegistry.java:1382)
09-10 11:16:33.363  1988  2190 E NfcManager: 	at android.app.ContextImpl.getSystemService(ContextImpl.java:1921)
09-10 11:16:33.363  1988  2190 E NfcManager: 	at android.content.ContextWrapper.getSystemService(ContextWrapper.java:803)
09-10 11:16:33.363  1988  2190 E NfcManager: 	at android.nfc.NfcAdapter.getDefaultAdapter(NfcAdapter.java:681)
09-10 11:16:33.363  1988  2190 E NfcManager: 	at com.android.systemui.qs.tiles.NfcTile.getAdapter(NfcTile.java:144)
09-10 11:16:33.363  1988  2190 E NfcManager: 	at com.android.systemui.qs.tiles.NfcTile.handleUpdateState(NfcTile.java:116)
09-10 11:16:33.363  1988  2190 E NfcManager: 	at com.android.systemui.qs.tiles.NfcTile.handleUpdateState(NfcTile.java:41)
09-10 11:16:33.363  1988  2190 E NfcManager: 	at com.android.systemui.qs.tileimpl.QSTileImpl.handleRefreshState(QSTileImpl.java:372)
09-10 11:16:33.363  1988  2190 E NfcManager: 	at com.android.systemui.qs.tileimpl.QSTileImpl$H.handleMessage(QSTileImpl.java:571)
09-10 11:16:33.363  1988  2190 E NfcManager: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-10 11:16:33.363  1988  2190 E NfcManager: 	at android.os.Looper.loop(Looper.java:223)
09-10 11:16:33.363  1988  2190 E NfcManager: 	at android.os.HandlerThread.run(HandlerThread.java:67)
```

No problems setting the NFC toggle inside of the Settings app, however

**Comment by thestinger** [comment]
That's a known issue from not having the SELinux commit ported. I'll file an issue about it.

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/os_issue_tracker/issues/286

**Comment by thestinger** [comment]
I also haven't filed issues for all of the SELinux migration work.
