### ISSUE TITLE
Issue on pixel 8

### ISSUE THREAD

**Issue by Ironman4eva** [GrapheneOS/os_issue_tracker#3185]
```
type: crash
osVersion: google/shiba/shiba:14/UQ1A.240105.004/2024012600:user/release-keys
package: com.android.vending:83873520
process: com.android.vending
processUptime: 99861 + 312 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 93

android.content.ActivityNotFoundException: No Activity found to handle Intent { act=com.google.android.gms.accountsettings.action.VIEW_SETTINGS pkg=com.google.android.gms (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2250)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1884)
	at android.app.Activity.startActivityForResult(Activity.java:5661)
	at zzzi.startActivityForResult(PG:50)
	at android.app.Activity.startActivityForResult(Activity.java:5581)
	at amaz.b(PG:33)
	at amce.a(PG:55)
	at win.a(PG:60)
	at amdp.onClick(PG:381)
	at vjt.b(PG:51)
	at aqzl.run(PG:30)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8279)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
```

**Comment by Ironman4eva** [comment]
Yes if it happens again I can't remembered exactly what it was I was doing
but I believe I was trying to open a google app when it happened. I will
def include that info if it happens again.
