### ISSUE TITLE
Error in Google Play Store

### ISSUE THREAD

**Issue by kommbek** [GrapheneOS/os_issue_tracker#3374]
Was unable to use google play store for about 24hrs as if there was no internet connection but only for the Play Store, app displayed broken satellite image and game. Internet was working normally with everything else on my Pixel 8. 

What did not work:
- restarting play store
- force quit and restart app 
- rebooting device

What worked:
I uninstalled and reinstalled google play store and google play services.

Logged in with yubikey and was presented the main page, crash occurred when going to update applications. 

```
type: crash
osVersion: google/shiba/shiba:14/AP1A.240305.019.A1/2024032100:user/release-keys
package: com.android.vending:83951820
process: com.android.vending
processUptime: 234374 + 416 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 99

java.lang.NullPointerException: Attempt to read from field 'hoj android.support.v7.widget.RecyclerView.W' on a null object reference in method 'void ld.k(android.view.View, int, boolean)'
	at ld.k(PG:16)
	at ld.adH(PG:2)
	at ld.adG(PG:2)
	at tww.c(PG:39)
	at com.google.android.finsky.layoutmanager.HybridLayoutManager.at(PG:9)
	at android.support.v7.widget.LinearLayoutManagerWithProxies.B(PG:13)
	at android.support.v7.widget.LinearLayoutManager.M(PG:45)
	at android.support.v7.widget.LinearLayoutManager.n(PG:743)
	at com.google.android.finsky.layoutmanager.HybridLayoutManager.n(PG:110)
	at android.support.v7.widget.RecyclerView.aO(PG:65)
	at android.support.v7.widget.RecyclerView.F(PG:74)
	at android.support.v7.widget.RecyclerView.onLayout(PG:6)
	at com.google.android.finsky.recyclerview.PlayRecyclerView.onLayout(PG:9)
	at android.view.View.layout(View.java:24722)
	at android.view.ViewGroup.layout(ViewGroup.java:6450)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24722)
	at android.view.ViewGroup.layout(ViewGroup.java:6450)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24722)
	at android.view.ViewGroup.layout(ViewGroup.java:6450)
	at hzz.onLayout(PG:256)
	at android.view.View.layout(View.java:24722)
	at android.view.ViewGroup.layout(ViewGroup.java:6450)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24722)
	at android.view.ViewGroup.layout(ViewGroup.java:6450)
	at aoyy.agW(PG:142)
	at aoza.j(PG:1)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.j(PG:1)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(PG:41)
	at android.view.View.layout(View.java:24722)
	at android.view.ViewGroup.layout(ViewGroup.java:6450)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24722)
	at android.view.ViewGroup.layout(ViewGroup.java:6450)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24722)
	at android.view.ViewGroup.layout(ViewGroup.java:6450)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24722)
	at android.view.ViewGroup.layout(ViewGroup.java:6450)
	at com.google.android.finsky.drawer.FinskyDrawerLayout.onLayout(PG:48)
	at android.view.View.layout(View.java:24722)
	at android.view.ViewGroup.layout(ViewGroup.java:6450)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24722)
	at android.view.ViewGroup.layout(ViewGroup.java:6450)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24722)
	at android.view.ViewGroup.layout(ViewGroup.java:6450)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24722)
	at android.view.ViewGroup.layout(ViewGroup.java:6450)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:24722)
	at android.view.ViewGroup.layout(ViewGroup.java:6450)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:807)
	at android.view.View.layout(View.java:24722)
	at android.view.ViewGroup.layout(ViewGroup.java:6450)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4485)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3786)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2659)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9789)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1399)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1408)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1008)
	at android.view.Choreographer.doFrame(Choreographer.java:938)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1382)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8532)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
```
[Google Play Store log c5ac5febe5ba.txt](https://github.com/GrapheneOS/os-issue-tracker/files/14742114/Google.Play.Store.log.c5ac5febe5ba.txt)
[System log 4b7168b12a5c.txt](https://github.com/GrapheneOS/os-issue-tracker/files/14742120/System.log.4b7168b12a5c.txt)

**Comment by muhomorr** [comment]
Is this a repetitive crash?

**Comment by kommbek** [comment]
No it's only done it once so far.

**Comment by kommbek** [comment]
Ok good to know. Merci!
