### ISSUE TITLE
music apps auto lock phone when used from a secondary profile in Android 11

### ISSUE THREAD

**Issue by cheapwater20** [GrapheneOS/os_issue_tracker#339]
Hello,
I have a Pixel 4 with the  latest GOS and after the update last night if I open up either app; Spotify or amazon music, it will auto lock my phone if I start to play a playlist, skip a track, or when a new song plays. I  also erased my profile on my phone, created a new profile, and reinstalled my apps including Spotify and Amazon Music.... Problem still persists.

Thank you

Phone info:
Model: Pixel 4
Android version: 11
Android security update: September 5, 2020
Mainline system update: 11
Kernal version: 4.14.180-00001-ga073e3de09c1
GrapheneOS/grapheneos.org#1 Tue 22 Sep 2020 09:44:09 AM EDT

Build number: RP1A.200720.009.2020.09.25.00

**Comment by cheapwater20** [comment]
When I skip a song, pause a song, start a play list.... The screen goes to my phones lock screen. Then I use my pin code to unlock the phone again. I also just factory reset my phone, installed my apps and the issue still persists.

**Comment by thestinger** [comment]
You'll need to provide logs from either `adb logcat` or the bug report capture tool within the OS.

We're not able to reproduce this issue.

Can you provide more information like your audio setup, etc. too?

**Comment by anupritaisno1** [comment]
cannot reproduce on pixel 4

**Comment by thestinger** [comment]
It sounds like a core system process is aborting, perhaps because hardened_malloc uncovers a bug. It sounds like you have an uncommon / special configuration which is causing the issue, such as a Bluetooth audio device using an older protocol that isn't being tested by us.

**Comment by cheapwater20** [comment]
Thank you folks for looking into this, I do appreciate it. I will figure out how to get those logs and post them here. I have attempted to play music through the spotify app on my daily driver profile and that is where I have the problems. My "Owner" profile is as Vanilla as it gets. I tried something out though. I went to my owner profile, downloaded F-Droid to download Aurora, and then downloaded bitwarden and spotify. I logged into spofity and it played just fine on the owner profile. Then I went to my Daily Driver Profile and played spotify and it played fine without any issues. I then confirmed this again and removed spotify from my Owner profile and then went into my Daily Driver profile and spotify would then autolock the phone every time I played a song or skipped a track. I then put Spotify back onto my "owner profile" and went back into my Daily Driver profile and then spotify played just fine. Also, I attempted to get logs, I logged into my owner profile and enabled developer options started recording but then I realized... will it still record while I go into my Daily Driver Profile? I apologize if I don't make sense.. there is a lot I don't understand, lol.

**Comment by cheapwater20** [comment]
To include more information about my audio setup, I connect via Bluetooth to a Ultimate Ears Wonderboom speaker, or an Anker Soundcore speaker, or an Anker Bluetooth receiver and it connects to my vehicles RCA cables.

**Comment by thestinger** [comment]
Does this issue happen when not connected to devices via Bluetooth?

**Comment by cheapwater20** [comment]
Yes Sir, it does. RIght now though, I have spotify (I'm not even logged into)on my Owner profile and I am Listening to music just fine on my Daily Driver Profile.

**Comment by anupritaisno1** [comment]
i have successfully reproduced this issue on the stock rom. can you file a bug on google's issuetracker?

i'll do it myself in a bit if you don't

**Comment by anupritaisno1** [comment]
@thestinger reword issue title to "music apps auto lock phone when used from a secondary profile"

**Comment by inthewaves** [comment]
Apparently this doesn't happen if Spotify is installed in both the admin/main user and the secondary user. Uninstalling Spotify from the main user results in these errors in logcat. It looks like to me it might be trying to get the package info as the main user for icons (these errors don't show up if Spotify is installed in the main profile)

```plain
10-04 11:43:42.105 21999 22066 E IconCompat: Unable to find pkg=com.spotify.music for icon
10-04 11:43:42.105 21999 22066 E IconCompat: android.content.pm.PackageManager: com.spotify.music
10-04 11:43:42.105 21999 22066 E IconCompat: at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:423)
10-04 11:43:42.105 21999 22066 E IconCompat: at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:412)
10-04 11:43:42.105 21999 22066 E IconCompat: at androidx.core.graphics.drawable.IconCompat.getResources(IconCompat.java:728)
10-04 11:43:42.105 21999 22066 E IconCompat: at androidx.core.graphics.drawable.IconCompat.createFromIcon(IconCompat.java:1025)
10-04 11:43:42.105 21999 22066 E IconCompat: at com.android.systemui.keyguard.KeyguardSliceProvider.addMediaLocked(KeyguardSliceProvider.java:241)
10-04 11:43:42.105 21999 22066 E IconCompat: at com.android.systemui.keyguard.KeyguardSliceProvider.onBindSlice(KeyguardSliceProvider.java:206)
10-04 11:43:42.105 21999 22066 E IconCompat: at androidx.slice.compat.SliceProviderWrapperContainer.onBindSlice(SliceProviderWrapperContainer.java:142)
10-04 11:43:42.105 21999 22066 E IconCompat: at android.app.slice.SliceProvider.onBindSliceStrict(SliceProvider.java:553)
10-04 11:43:42.105 21999 22066 E IconCompat: at android.app.slice.SliceProvider.handleBindSlice(SliceProvider.java:467)
10-04 11:43:42.105 21999 22066 E IconCompat: at android.app.slice.SliceProvider.call(SliceProvider.java:366)
10-04 11:43:42.105 21999 22066 E IconCompat: at androidx.slice.compat.SliceProviderWrapperContainer.call(SliceProviderWrapperContainer.java:122)
10-04 11:43:42.105 21999 22066 E IconCompat: at android.content.ContentProvider.call(ContentProvider.java:2448)
10-04 11:43:42.105 21999 22066 E IconCompat: at android.content.ContentProvider.call(ContentProvider.java:517)
10-04 11:43:42.105 21999 22066 E IconCompat: at android.content.ContentProviderClient.call(ContentProviderClient.java:603)
10-04 11:43:42.105 21999 22066 E IconCompat: at android.content.ContentProviderClient.call(ContentProviderClient.java:591)
10-04 11:43:42.105 21999 22066 E IconCompat: at android.app.slice.SliceManager.bindSlice(SliceManager.java:256)
10-04 11:43:42.105 21999 22066 E IconCompat: at androidx.slice.Slice.callBindSlice(Slice.java:637)
10-04 11:43:42.105 21999 22066 E IconCompat: at androidx.slice.Slice.bindSlice(Slice.java:627)
10-04 11:43:42.105 21999 22066 E IconCompat: at androidx.slice.SliceViewManagerBase.run(SliceViewManagerBase.java:134)
10-04 11:43:42.105 21999 22066 E IconCompat: at android.os.AsyncTask.run(AsyncTask.java:305)
10-04 11:43:42.105 21999 22066 E IconCompat: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-04 11:43:42.105 21999 22066 E IconCompat: at java.util.concurrent.ThreadPoolExecutor.run(ThreadPoolExecutor.java:641)
10-04 11:43:42.105 21999 22066 E IconCompat: at java.lang.Thread.run(Thread.java:923)
10-04 11:43:42.106 21999 22066 E IconCompat: Unable to find pkg=com.spotify.music for icon
10-04 11:43:42.106 21999 22066 E IconCompat: android.content.pm.PackageManager: com.spotify.music
10-04 11:43:42.106 21999 22066 E IconCompat: at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:423)
10-04 11:43:42.106 21999 22066 E IconCompat: at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:412)
10-04 11:43:42.106 21999 22066 E IconCompat: at androidx.core.graphics.drawable.IconCompat.getResources(IconCompat.java:728)
10-04 11:43:42.106 21999 22066 E IconCompat: at androidx.core.graphics.drawable.IconCompat.createFromIcon(IconCompat.java:1025)
10-04 11:43:42.106 21999 22066 E IconCompat: at androidx.slice.SliceConvert.wrap(SliceConvert.java:118)
10-04 11:43:42.106 21999 22066 E IconCompat: at androidx.slice.SliceConvert.wrap(SliceConvert.java:114)
10-04 11:43:42.106 21999 22066 E IconCompat: at androidx.slice.SliceConvert.wrap(SliceConvert.java:114)
10-04 11:43:42.106 21999 22066 E IconCompat: at androidx.slice.Slice.callBindSlice(Slice.java:636)
10-04 11:43:42.106 21999 22066 E IconCompat: at androidx.slice.Slice.bindSlice(Slice.java:627)
10-04 11:43:42.106 21999 22066 E IconCompat: at androidx.slice.SliceViewManagerBase.run(SliceViewManagerBase.java:134)
10-04 11:43:42.106 21999 22066 E IconCompat: at android.os.AsyncTask.run(AsyncTask.java:305)
10-04 11:43:42.106 21999 22066 E IconCompat: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-04 11:43:42.106 21999 22066 E IconCompat: at java.util.concurrent.ThreadPoolExecutor.run(ThreadPoolExecutor.java:641)
10-04 11:43:42.106 21999 22066 E IconCompat: at java.lang.Thread.run(Thread.java:923)
10-04 11:43:42.109 21999 21999 E Icon    : Unable to find pkg=com.spotify.music for icon Icon(typ=RESOURCE pkg=com.spotify.music id=0x7f080347)
10-04 11:43:42.109 21999 21999 E Icon    : android.content.pm.PackageManager: com.spotify.music
10-04 11:43:42.109 21999 21999 E Icon    : at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:423)
10-04 11:43:42.109 21999 21999 E Icon    : at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:412)
10-04 11:43:42.109 21999 21999 E Icon    : at android.graphics.drawable.Icon.loadDrawableInner(Icon.java:366)
10-04 11:43:42.109 21999 21999 E Icon    : at android.graphics.drawable.Icon.loadDrawable(Icon.java:334)
10-04 11:43:42.109 21999 21999 E Icon    : at androidx.core.graphics.drawable.IconCompat.loadDrawable(IconCompat.java:628)
10-04 11:43:42.109 21999 21999 E Icon    : at com.android.keyguard.KeyguardSliceView.showSlice(KeyguardSliceView.java:281)
10-04 11:43:42.109 21999 21999 E Icon    : at com.android.keyguard.KeyguardSliceView.onChanged(KeyguardSliceView.java:349)
10-04 11:43:42.109 21999 21999 E Icon    : at com.android.keyguard.KeyguardSliceView.onChanged(KeyguardSliceView.java:86)
10-04 11:43:42.109 21999 21999 E Icon    : at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
10-04 11:43:42.109 21999 21999 E Icon    : at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
10-04 11:43:42.109 21999 21999 E Icon    : at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
10-04 11:43:42.109 21999 21999 E Icon    : at androidx.lifecycle.LiveData.run(LiveData.java:93)
10-04 11:43:42.109 21999 21999 E Icon    : at android.os.Handler.handleCallback(Handler.java:938)
10-04 11:43:42.109 21999 21999 E Icon    : at android.os.Handler.dispatchMessage(Handler.java:99)
10-04 11:43:42.109 21999 21999 E Icon    : at android.os.Looper.loop(Looper.java:223)
10-04 11:43:42.109 21999 21999 E Icon    : at android.app.ActivityThread.main(ActivityThread.java:7656)
10-04 11:43:42.109 21999 21999 E Icon    : at java.lang.reflect.Method.invoke(Native Method)
10-04 11:43:42.109 21999 21999 E Icon    : at com.android.internal.os.RuntimeInit.run(RuntimeInit.java:592)
10-04 11:43:42.109 21999 21999 E Icon    : at com.android.internal.os.ExecInit.main(ExecInit.java:43)
10-04 11:43:42.109 21999 21999 E Icon    : at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
10-04 11:43:42.109 21999 21999 E Icon    : at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
10-04 11:43:42.082  1830  1830 I chatty  : uid=1000(system) SessionRecordTh identical 2 lines
10-04 11:43:42.083  1830  1830 I binder  : 1345:1830 transaction failed 29189/-22, size 1064-8 line 3186
10-04 11:43:42.103  9061  9061 I afe_tdm_port_start: top_id:10001ccc acdb_id:512 port_id:0x9011
10-04 11:43:42.130  1728  9061 I soundtrigger: audio_extn_sound_trigger_update_stream_status: send event 3: usecase id 0, type 0
10-04 11:43:42.130  1728  9061 D sound_trigger_platform: platform_stdev_check_and_update_concurrency: concurrency active 0, tx 0, rx 1, concurrency session_allowed 1
10-04 11:43:42.130  1728  9061 D sound_trigger_platform: platform_stdev_check_concurrency_supported: capture concurrency  allowed, usecase type 0 voice_concur 0 voip_concur 0
10-04 11:43:42.131  1728  9061 D msm8974_platform: Setting audio calibration for snd_device(2) acdb_id(513)
10-04 11:43:42.132  1728  9061 E ACDB-LOADER: [acdb_loader_adsp_set_audio_cal] active device/stream not found (result=-100) for topology 0x1000dffb and apptype 0x11134
10-04 11:43:42.132  1728  9061 E ACDB-LOADER: [acdb_loader_adsp_set_audio_cal] set parameters failed with status -100
10-04 11:43:42.132  1728  9061 D msm8974_platform: Setting audio calibration for snd_device(2) acdb_id(513)
10-04 11:43:42.134  1728  9061 D msm8974_platform: Setting audio calibration for snd_device(2) acdb_id(513)
10-04 11:43:42.134  1728  9061 E ACDB-LOADER: [acdb_loader_adsp_set_audio_cal] active device/stream not found (result=-100) for topology 0x1000dffb and apptype 0x11134
10-04 11:43:42.134  1728  9061 E ACDB-LOADER: [acdb_loader_adsp_set_audio_cal] set parameters failed with status -100
10-04 11:43:42.134  1728  9061 D msm8974_platform: Setting audio calibration for snd_device(2) acdb_id(513)
10-04 11:43:42.134  1728  9061 D audio_hw_waves: print_state_log: send volume table -(0,0.000000,F),(1,0.000000,F),(2,0.000000,F),(3,0.029460,T),(4,0.000000,F),(5,0.000000,F)
10-04 11:43:42.134  1728  9061 D ACDB-LOADER: ACDB -> send_audio_cal, acdb_id = 513, path = 0, app id = 0x11134, sample rate = 48000
10-04 11:43:42.134  1728  9061 D ACDB-LOADER: ACDB -> send_asm_topology
10-04 11:43:42.134  1728  9061 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TOPOLOGY_ID
10-04 11:43:42.134  1728  9061 D ACDB-LOADER: ACDB -> send_adm_topology
10-04 11:43:42.134  1728  9061 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TOPOLOGY_ID
10-04 11:43:42.134  1728  9061 D ACDB-LOADER: ACDB -> send_audtable
10-04 11:43:42.135  1728  9061 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE_SIZE
10-04 11:43:42.135  1728  9061 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE
10-04 11:43:42.135  1728  9061 D ACDB-LOADER: ACDB -> AUDIO_SET_AUDPROC_CAL
10-04 11:43:42.135  1728  9061 D ACDB-LOADER: ACDB -> send_audvoltable
10-04 11:43:42.135  1728  9061 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_VOL_STEP_TABLE_SIZE
10-04 11:43:42.135  1728  9061 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_STEP_TABLE, vol index 0
10-04 11:43:42.135  1728  9061 D android.hardware.audio.service: Failed to fetch the lookup information of the device 00000201 
10-04 11:43:42.135  1728  9061 E ACDB-LOADER: Error: ACDB AudProc vol returned = -19
10-04 11:43:42.135  1728  9061 D ACDB-LOADER: ACDB -> AUDIO_SET_VOL_CAL cal type = 12
10-04 11:43:42.135  1728  9061 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TABLE_SIZE
10-04 11:43:42.135  1728  9061 D ACDB-LOADER: ACDB -> send_audstrmtable
10-04 11:43:42.135  1728  9061 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TABLE_V2
10-04 11:43:42.135  1728  9061 D ACDB-LOADER: ACDB -> audstrm_cal->cal_type.cal_data.cal_size = 488
10-04 11:43:42.135  1728  9061 D ACDB-LOADER: ACDB -> send_afe_topology
10-04 11:43:42.135  1728  9061 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AFE_TOPOLOGY_ID
10-04 11:43:42.135  1728  9061 D ACDB-LOADER: ACDB -> GET_AFE_TOPOLOGY_ID for adcd_id 513, Topology Id 10000ccc
10-04 11:43:42.135  1728  9061 D ACDB-LOADER: ACDB -> send_afe_cal
10-04 11:43:42.135  1728  9061 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AFE_COMMON_TABLE_SIZE
10-04 11:43:42.135  1728  9061 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AFE_COMMON_TABLE
10-04 11:43:42.135  1728  9061 D ACDB-LOADER: ACDB -> AUDIO_SET_AFE_CAL
10-04 11:43:42.135  1728  9061 D ACDB-LOADER: ACDB -> send_hw_delay : acdb_id = 513 path = 0
10-04 11:43:42.135  1728  9061 D ACDB-LOADER: ACDB -> ACDB_AVSYNC_INFO: ACDB_CMD_GET_DEVICE_PROPERTY
10-04 11:43:42.135  1728  9061 D audio_hw_primary: enable_audio_route: usecase(0) apply and update mixer path: deep-buffer-playback speaker
10-04 11:43:42.135  1728  9061 D audio_route: Apply path: deep-buffer-playback speaker
10-04 11:43:42.156  9061  9061 I afe_tdm_port_start: top_id:10000ccc acdb_id:513 port_id:0x9010
10-04 11:43:42.196  1728  9061 D audio_hw_primary: out_write: retry previous failed cal level set
10-04 11:43:42.291  1727  1780 D AudioFlinger: mixer(0x609191e000) throttle end: throttle time(46)
10-04 11:43:42.330 21999 21999 D InterruptionStateProvider: No alerting: filtered notification: 10|com.spotify.music|2131430415|null|1010121
10-04 11:43:42.331 21999 21999 D InterruptionStateProvider: No alerting: filtered notification: 10|com.spotify.music|2131430415|null|1010121
10-04 11:43:42.336 21999 22045 E Icon    : Unable to find pkg=com.spotify.music for icon Icon(typ=RESOURCE pkg=com.spotify.music id=0x7f080347)
10-04 11:43:42.336 21999 22045 E Icon    : android.content.pm.PackageManager: com.spotify.music
10-04 11:43:42.336 21999 22045 E Icon    : at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:423)
10-04 11:43:42.336 21999 22045 E Icon    : at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:412)
10-04 11:43:42.336 21999 22045 E Icon    : at android.graphics.drawable.Icon.loadDrawableInner(Icon.java:366)
10-04 11:43:42.336 21999 22045 E Icon    : at android.graphics.drawable.Icon.loadDrawable(Icon.java:334)
10-04 11:43:42.336 21999 22045 E Icon    : at com.android.systemui.media.MediaDataManager.loadMediaDataInBg(MediaDataManager.kt:363)
10-04 11:43:42.336 21999 22045 E Icon    : at com.android.systemui.media.MediaDataManager.access(MediaDataManager.kt:89)
10-04 11:43:42.336 21999 22045 E Icon    : at com.android.systemui.media.MediaDataManager.run(MediaDataManager.kt:241)
10-04 11:43:42.336 21999 22045 E Icon    : at android.os.Handler.handleCallback(Handler.java:938)
10-04 11:43:42.336 21999 22045 E Icon    : at android.os.Handler.dispatchMessage(Handler.java:99)
10-04 11:43:42.336 21999 22045 E Icon    : at android.os.Looper.loop(Looper.java:223)
10-04 11:43:42.336 21999 22045 E Icon    : at android.os.HandlerThread.run(HandlerThread.java:67)
10-04 11:43:42.337 21999 22045 E AndroidRuntime: FATAL EXCEPTION: SysUiBg
10-04 11:43:42.337 21999 22045 E AndroidRuntime: Process: com.android.systemui, PID: 21999
10-04 11:43:42.337 21999 22045 E AndroidRuntime: java.lang.IllegalStateException: sbn.notification.smallIcon.loadDrawable(context) must not be null
10-04 11:43:42.337 21999 22045 E AndroidRuntime: at com.android.systemui.media.MediaDataManager.loadMediaDataInBg(MediaDataManager.kt:363)
10-04 11:43:42.337 21999 22045 E AndroidRuntime: at com.android.systemui.media.MediaDataManager.access(MediaDataManager.kt:89)
10-04 11:43:42.337 21999 22045 E AndroidRuntime: at com.android.systemui.media.MediaDataManager.run(MediaDataManager.kt:241)
10-04 11:43:42.337 21999 22045 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:938)
10-04 11:43:42.337 21999 22045 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:99)
10-04 11:43:42.337 21999 22045 E AndroidRuntime: at android.os.Looper.loop(Looper.java:223)
10-04 11:43:42.337 21999 22045 E AndroidRuntime: at android.os.HandlerThread.run(HandlerThread.java:67)
10-04 11:43:42.341  1345 22098 I DropBoxManagerService: add tag=system_app_crash isTagEnabled=true flags=0x2
10-04 11:43:42.341  1345  2468 W ActivityManager: Process com.android.systemui has crashed too many times: killing!
10-04 11:43:42.342  1345  1546 W ActivityManager: Skipping crash dialog of ProcessRecord{d35b54a 21999:com.android.systemui/u0a108}: background
10-04 11:43:42.343 21999 22045 I Process : Sending signal. PID: 21999 SIG: 9
10-04 11:43:42.446  1345  1718 W InputDispatcher: channel '67de1fa ScreenDecorOverlayBottom (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
10-04 11:43:42.446  1345  1718 E InputDispatcher: channel '67de1fa ScreenDecorOverlayBottom (server)' ~ Channel is unrecoverably broken and will be disposed!
10-04 11:43:42.446  1345  1718 W InputDispatcher: channel 'cf65ad8 ScreenDecorOverlay (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
10-04 11:43:42.446  1345  1718 E InputDispatcher: channel 'cf65ad8 ScreenDecorOverlay (server)' ~ Channel is unrecoverably broken and will be disposed!
10-04 11:43:42.446  1345  1718 W InputDispatcher: channel '31cf7da StatusBar (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
10-04 11:43:42.446  1345  1718 E InputDispatcher: channel '31cf7da StatusBar (server)' ~ Channel is unrecoverably broken and will be disposed!
10-04 11:43:42.446  1345  1718 W InputDispatcher: channel '6851d34 NavigationBar0 (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
10-04 11:43:42.446  1345  1718 E InputDispatcher: channel '6851d34 NavigationBar0 (server)' ~ Channel is unrecoverably broken and will be disposed!
10-04 11:43:42.448  1345  2080 I StatusBarManagerService: binder died for pkg=com.android.systemui
```

**Comment by inthewaves** [comment]
Putting this log in frameworks/base/core/java/android/app/ApplicationPackageManager.java confirms it:

```java
@Override
public ApplicationInfo getApplicationInfoAsUser(String packageName, int flags, int userId)
        throws NameNotFoundException {
    ApplicationInfo ai = getApplicationInfoAsUserCached(
                    packageName,
                    updateFlagsForApplication(flags, userId),
                    userId);
    if (ai == null) {
        Log.i(TAG, "DEBUG: FAILED TO GET APPLICATION INFO for " + packageName + " for user: " + userId);
        throw new NameNotFoundException(packageName);
    }
    return maybeAdjustApplicationInfo(ai);
}
```

Pressing the forward button in Spotify gets these in logcat

```plain
$ adb logcat -e "DEBUG"
10-04 12:02:49.809  1888  5610 I ApplicationPackageManager: DEBUG: FAILED TO GET APPLICATION INFO for com.spotify.music for user: 0
10-04 12:02:49.811  1888  5610 I ApplicationPackageManager: DEBUG: FAILED TO GET APPLICATION INFO for com.spotify.music for user: 0
10-04 12:02:49.831  1888  1888 I ApplicationPackageManager: DEBUG: FAILED TO GET APPLICATION INFO for com.spotify.music for user: 0
10-04 12:02:50.546  1888  2106 I ApplicationPackageManager: DEBUG: FAILED TO GET APPLICATION INFO for com.spotify.music for user: 0
```

**Comment by inthewaves** [comment]
Even worse for NewPipe since it'll crash and take you to the lockscreen as soon as you play the video, and then unlocking immediately crashes it:

```
10-04 12:10:01.793 11212 11243 I ApplicationPackageManager: DEBUG: FAILED TO GET APPLICATION INFO for org.schabi.newpipe for user: 0
10-04 12:10:01.794 11212 11243 E Icon    : Unable to find pkg=org.schabi.newpipe for icon Icon(typ=RESOURCE pkg=org.schabi.newpipe id=0x7f080115)
10-04 12:10:01.794 11212 11243 E Icon    : android.content.pm.PackageManager$NameNotFoundException: org.schabi.newpipe
10-04 12:10:01.794 11212 11243 E Icon    : 	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:424)
10-04 12:10:01.794 11212 11243 E Icon    : 	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:412)
10-04 12:10:01.794 11212 11243 E Icon    : 	at android.graphics.drawable.Icon.loadDrawableInner(Icon.java:366)
10-04 12:10:01.794 11212 11243 E Icon    : 	at android.graphics.drawable.Icon.loadDrawable(Icon.java:334)
10-04 12:10:01.794 11212 11243 E Icon    : 	at com.android.systemui.media.MediaDataManager.loadMediaDataInBg(MediaDataManager.kt:363)
10-04 12:10:01.794 11212 11243 E Icon    : 	at com.android.systemui.media.MediaDataManager.access$loadMediaDataInBg(MediaDataManager.kt:89)
10-04 12:10:01.794 11212 11243 E Icon    : 	at com.android.systemui.media.MediaDataManager$loadMediaData$1.run(MediaDataManager.kt:241)
10-04 12:10:01.794 11212 11243 E Icon    : 	at android.os.Handler.handleCallback(Handler.java:938)
10-04 12:10:01.794 11212 11243 E Icon    : 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-04 12:10:01.794 11212 11243 E Icon    : 	at android.os.Looper.loop(Looper.java:223)
10-04 12:10:01.794 11212 11243 E Icon    : 	at android.os.HandlerThread.run(HandlerThread.java:67)
10-04 12:10:01.795 11212 11243 E AndroidRuntime: FATAL EXCEPTION: SysUiBg
10-04 12:10:01.795 11212 11243 E AndroidRuntime: Process: com.android.systemui, PID: 11212
10-04 12:10:01.795 11212 11243 E AndroidRuntime: java.lang.IllegalStateException: sbn.notification.smallIcon.loadDrawable(context) must not be null
10-04 12:10:01.795 11212 11243 E AndroidRuntime: 	at com.android.systemui.media.MediaDataManager.loadMediaDataInBg(MediaDataManager.kt:363)
10-04 12:10:01.795 11212 11243 E AndroidRuntime: 	at com.android.systemui.media.MediaDataManager.access$loadMediaDataInBg(MediaDataManager.kt:89)
10-04 12:10:01.795 11212 11243 E AndroidRuntime: 	at com.android.systemui.media.MediaDataManager$loadMediaData$1.run(MediaDataManager.kt:241)
10-04 12:10:01.795 11212 11243 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
10-04 12:10:01.795 11212 11243 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-04 12:10:01.795 11212 11243 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
10-04 12:10:01.795 11212 11243 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:67)
10-04 12:10:01.799  1326 11297 I DropBoxManagerService: add tag=system_app_crash isTagEnabled=true flags=0x2
```
