### ISSUE TITLE
System Server Crash

### ISSUE THREAD

**Issue by TuxLux40** [GrapheneOS/os_issue_tracker#3663]
```
type: crash
SystemUptimeMs: 3406176
Process: system_server
Build: google/cheetah/cheetah:14/AP2A.240605.024/2024061400:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032 SQLITE_READONLY_DBMOVED)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:926)
	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:780)
	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:67)
	at android.database.sqlite.SQLiteDatabase.delete(SQLiteDatabase.java:2006)
	at com.android.server.accounts.AccountsDb.deleteGrantsByUid(AccountsDb.java:917)
	at com.android.server.accounts.AccountManagerService.purgeOldGrants(AccountManagerService.java:1452)
	at com.android.server.accounts.AccountManagerService.purgeOldGrantsAll(AccountManagerService.java:1430)
	at com.android.server.accounts.AccountManagerService.-$$Nest$mpurgeOldGrantsAll(AccountManagerService.java:0)
	at com.android.server.accounts.AccountManagerService$1$1.run(AccountManagerService.java:330)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

**Comment by Survivor1905** [comment]
Yes, sorry.This time it happened when I tried to uninstall the Google App. I don't remember what triggered it the first time. However, I had the error that the system GUI wasn't responding quite often over the last couple of weeks, but this was the first time the phone restarted. At least I think it did, because it showed the GOS logo. I had a second profile for work with Play Services installed in both profiles. Shortly after I installed Insular and deleted the secondary profile, it started behaving strangely. From what I could understand from the log, it had something to do with the Account Manager, so I disabled multiple users.

**Comment by mar0ni** [comment]
Pixel 8a also crashes when switching to secondary profile with Google Play Services installed.

`
type: crash
SystemUptimeMs: 344451
Process: system_server
Build: google/akita/akita:14/AP2A.240605.024/2024062000:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.AssertionError: java.lang.IllegalArgumentException: unregistered listener cannot be flushed
	at android.location.provider.LocationProviderBase$Service.lambda$flush$1(LocationProviderBase.java:349)
	at android.location.provider.LocationProviderBase$Service$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at com.android.server.SystemServer.run(SystemServer.java:1024)
	at com.android.server.SystemServer.main(SystemServer.java:702)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:872)
Caused by: java.lang.IllegalArgumentException: unregistered listener cannot be flushed
	at com.android.internal.util.Preconditions.checkArgument(Preconditions.java:60)
	at android.location.LocationManager.requestFlush(LocationManager.java:1718)
	at com.android.location.gnss.GnssOverlayLocationProvider.onFlush(GnssOverlayLocationProvider.java:112)
	at android.location.provider.LocationProviderBase$Service.flush(LocationProviderBase.java:344)
	at com.android.server.location.provider.proxy.ProxyLocationProvider$2.run(ProxyLocationProvider.java:207)
	at com.android.server.servicewatcher.ServiceWatcherImpl$MyServiceConnection.runOnBinder(ServiceWatcherImpl.java:257)
	at com.android.server.servicewatcher.ServiceWatcherImpl.lambda$runOnBinder$0(ServiceWatcherImpl.java:126)
	at com.android.server.servicewatcher.ServiceWatcherImpl.$r8$lambda$GCGDYqQZRK7jCQUNZnY8QjXgR2Y(ServiceWatcherImpl.java:0)
	at com.android.server.servicewatcher.ServiceWatcherImpl$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)
`

**Comment by timonoj** [comment]
Pixel 7 also. It crashes when returning to main profile from a secondary profile. Both with gservices.
