### ISSUE TITLE
PWAs and shortcuts disappear after reboot

### ISSUE THREAD

**Issue by ghost** [GrapheneOS/os_issue_tracker#3677]
In both Brave and Vanadium, my PWAs always disappear from the homescreen after the OS reboots. I'm not sure why this happens but it's a very frustrating bug.

**Comment by bakeromso** [comment]
This happens for me too quite often, but I thought it was after the update, as that contains a reboot too. I must add, this doesn't happen consistently for me after every update.

**Comment by BjGoCraft** [comment]
For me it happened after the reboots from the last two updates. Normal reboots don't remove anything for me. Very annoying if you have many PWAs

**Comment by onnyyonn** [comment]
This happened to me after the most recent update.

**Comment by AxFaure** [comment]
Hi !

I found a way to reproduce this behavior. I am not sure we only have a single root cause for all the issues mentioned in this thread but hopefully this might help solving at least some of them.

Basically if I create a shortcut to this [Etherfields app](https://etherfields-secret-scripts.web.app/) (or to [this one](https://etherfieldsapp.awakenrealms.com/) which as far as I can tell is the same app under a different domain) in my launcher and then reboot (or close and reopen the session), all my PWAs and shortcuts are gone.
It does not seem to trigger with the other apps and shortcuts I use (things like linkedin, deliveroo or even this forum) but with the Etherfields app I have been able to reproduce it with every single attempt.

I can reproduce the issue both in main and secondary profiles It does not wipe PWAs of other profiles though. If I create the faulty app in a profile all other PWAs in this profile will disappear but other profiles won't be affected.

For reference, I run version 2024103100 of GrapheneOS (although it did also occur in the previous one) on a Pixel8 and my apps are up to date (Vanadium and webview packages are in version 130.0.6723.86.0)
I only use Vanadium for my shortcuts and PWAs, I don't even have another browser installed. I do not create them from a private tab. And I use the original launcher. So this should be pretty much the standard/vanilla setup.

For the record, this issue was first mentioned on the forum in [this thread](https://discuss.grapheneos.org/d/9184-webapps-disappear-upon-restarting-phone/20) and another user confirmed being able to reproduce the issue even when adding the Etherfields app from Brave.

**Comment by fincentxyz** [comment]
Hi, my Web Apps / PWA's have been disappearing after the 2024112700 update. I re-added them, but now they've disappeared again after the 2024120200 update.

A regular reboot doesn't make them disappear. Only after a reboot for an update, since 2024112700 they disappear.

The only widget I use (Proton Calendar) doesn't disappear.

**Comment by fincentxyz** [comment]
> We only fixed this upstream bug for widgets so far, not shortcuts / PWAs.

Thank you! I'm glad you are aware of the issue, I hope it will be fixed soon.

Update 2024120400 did not remove the only PWA I added again after the previous update. I was hesitant to add them all back. But I suppose the issue does not have to do with the amount of shortcuts / PWAs.

**Comment by fincentxyz** [comment]
Update 2024120900 removed all my PWAs & shortcuts again.

**Comment by therealsupermax** [comment]
I just did a random restart (no call for an update) just to do so; haven't done one in a bit. 

Just lost all homescreen bookmarks & PWA's. I've done many restarts like this with no update. Never have lost anything before. 


I rarely use other profiles, but just 1 hour before I did the restart, I switched over to one of my other profiles, just to see what I had there. Immediately went back to Admin profile. 
About 60 minutes later, I decided to do a restart. Restarted fine, opened and saw all homescreen bookmarks & PWA's gone. 
Maybe this was the cause?

**Comment by BjGoCraft** [comment]
> This bug didn't occur to me for a while, can anyone try again?

The bug still occurred after the last update reboot on my device

**Comment by ggennrich** [comment]
This should be flagged as a critical issue. With the number of updates and reboots that happen with GrpaheneOS, it renders PWAs and shortcuts as useless. We don't want to have to keep installing all our PWAs.

**Comment by ggennrich** [comment]
@thestinger that's not an appropriate solution when you have users like myself who do not use Chrome for privacy reasons. It is a data harvesting app and I'll never use it. Vanadium strips all that garbage out. 

It would be helpful if you provided some detailed information as to how this is being dealt with and when this started. This bug was reported 10 months ago but I only have experienced it in the last month so there is some strange stuff happening.

**Comment by ggennrich** [comment]
@thestinger Thanks, that is helpful. Do you know why some users like myself are only recently experiencing this? I've been using GrapheneOS since August of 2024 with PWAs. It has only been in the last month where they disappear now after every update or restart.

**Comment by ggennrich** [comment]
@thestinger Not that I'm aware of. I'm not entirely sure what those two things mean either. How can I check?

**Comment by ggennrich** [comment]
I only have a single user account on my phone and have always.

**Comment by onnyyonn** [comment]
If I may add my own data point, this bug impacted me only once so far. And at that time, I was not using private space, or work profile, or a secondary user.

**Comment by ggennrich** [comment]
> Do you use Private Space or a work profile?

I do not. Just to gather more data for you I tested it in Vanadium, Chrome, and Kiwi Browser. After reboot they all disappeared. I then installed Firefox and tried and it did not disappear. This leads me to believe it is a Chromium based problem with either ASOT core or GrapheneOS. Since I don't have another phone with stock Android, I can't confirm that. 

For now, using FF works for me given it is private (for the most part) and secure.

**Comment by ggennrich** [comment]
Noted. Thanks for clarifying. Reinstalling PWAs on every reboot is, however, not something I'm willing to do when I have almost a dozen of them. I'll stick with FF for now since they don't disappear on reboot

**Comment by joshlupo** [comment]
Any reboot is causing all my PWAs to be removed and I have to reinstall them. I use Brave browser and I have only ever used the default account/profile.

**Comment by joshlupo** [comment]
> You are not bombarded with updates and if you want to disable them happening automatically and choose exactly when it happens, you can do that, but it's not at all recommended. There's also no automatic booting into the new update unless you enabled that toggle or set locked device auto-reboot to a low value occurring during your regular usage patterns.

it happens with normal reboots without an update as well. If I forget to charge my phone I lose my PWAs

**Comment by joshlupo** [comment]
> If you don't have sandboxed Google Play, it might not use WebAPKs.

I do have Sandboxed Google Play

**Comment by youreTheCommitToMyPR** [comment]
Just happened to me again, I was switching around between profiles, don't even know what exactly, then suddenly I noticed my incognito tab shortcut, other shortcuts, PWAs all disappeared. One notable effect is that long pressing on Vanadium icon does not show the Incognito tab option, only after I open it.

<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/98f6ca03-c656-42a2-ad8f-94a6aea41a21" />

**Comment by youreTheCommitToMyPR** [comment]
> I can consistently reproduce this using auto-reboot. I have it set to 8 hours, and every morning all of my Vanadium PWAs and shortcuts disappear from the home screen. Normal reboots are fine.

I will test this

**Comment by An-anonymous-coder** [comment]
Note: It seems to only reproduce if there is a PWA actually installed, otherwise it fails.

**Comment by hilburger** [comment]
Can confirm this, too. I am losing all my shortcuts in my non-admin daily profile each time I switch from it to admin and back. 
Each time the shortcuts are gone like after any reboot. 
It doesn't matter if Brave or Vanadium shortcuts. 
Running Graphine OS for about 9 months.

**Comment by hilburger** [comment]
> Can confirm this, too. I am losing all my shortcuts in my non-admin daily profile each time I switch from it to admin and back. Each time the shortcuts are gone like after any reboot. It doesn't matter if Brave or Vanadium shortcuts. Running Graphine OS for about 9 months.

Just be complete: 
The admin/owner is not affected.

**Comment by An-anonymous-coder** [comment]
I use the owner profile.

**Comment by Lppsoeht** [comment]
FYI I think this can be partially fixed, or at least I managed to do so, by enabling the specific profile to run in background.
The only profiles where PWA and shortcuts don't persist for me in multiple devices are new ones and those not allowed to run in background.
I have two profiles always running in background and in those shortcuts persist, maybe not from first time but after a while.

**Comment by thestinger** [comment]
It may be specifically triggered by end session.

**Comment by Lppsoeht** [comment]
To be more correct, one of the two profiles isn't always running in background, I use that button at least once a day on it.
By years of testing it seems that once it works on a profile it never stops working. Tested for years, also rn on those 2 with end session and I confirm they're not affected, in any case.

**Comment by youreTheCommitToMyPR** [comment]
Happened in secondary profile allowed to run in background. I often use End sessions and I also have auto reboot both at install and the timer.

**Comment by Lppsoeht** [comment]
Weirdly enough after over a year that it never happened on a profile today it happened. Just after a reboot.

**Comment by inthewaves** [comment]
Unable to reproduce this issue currently

When the issue happens again, please immediately obtain logs from Settings -> Apps -> See all apps -> Search for Launcher -> View logs (the default Launcher has code that may log stuff out when it delete shortcuts). You can post the log here if it doesn't appear to have sensitive info. It's important to do it right away after you notice shortcuts disappear, since logcat has limited storage and won't store logs forever.

Please consider also sending a system log when the issue happens again from Main user -> System -> View logs so that we can see what system_server is doing. The full system log can contain sensitive info, so you can send to logs@grapheneos.org with a reference to this issue (and add something like @inthewaves)

**Comment by DaddyAG** [comment]
@inthewaves sent you logs over the weekend. Logs are after manually rebooting phone from "power button - reboot".
Not sure if they show PWA deletion after reboot or it's done before reboot.

**Comment by realfunnyguy** [comment]
still not fixed unfortunately. If any further logs are needed i can provide.

**Comment by enyh2024** [comment]
## Reproducible root cause: an oversized `maskable` icon overflows Modified UTF-8 and wipes the browser's entire shortcut file

I can reproduce this deterministically. The trigger is installing a PWA whose manifest declares a `purpose: "maskable"` icon above roughly 64 KB **encoded** size. On the next reboot, every PWA launcher entry belonging to the browser is gone — not just the one that was installed.

### Stack trace

Logged at **install time**, not at boot:

```
E ShortcutService: Failed to write to file /data/system_ce/0/shortcut_service/packages/app.vanadium.browser.xml
E ShortcutService: java.io.IOException: Modified UTF-8 length too large: -280580
E ShortcutService:   at com.android.internal.util.ArtFastDataOutput.writeUTF(ArtFastDataOutput.java:93)
E ShortcutService:   at com.android.modules.utils.BinaryXmlSerializer.writeToken(BinaryXmlSerializer.java:110)
E ShortcutService:   at com.android.modules.utils.BinaryXmlSerializer.text(BinaryXmlSerializer.java:335)
E ShortcutService:   at com.android.internal.util.XmlUtils.writeValueXml(XmlUtils.java:816)
E ShortcutService:   at com.android.internal.util.XmlUtils.writeMapXml(XmlUtils.java:483)
E ShortcutService:   at android.os.PersistableBundle.saveToXml(PersistableBundle.java:308)
E ShortcutService:   at com.android.server.pm.ShortcutService.writeTagExtra(ShortcutService.java:1021)
E ShortcutService:   at com.android.server.pm.ShortcutPackage.saveShortcut(ShortcutPackage.java:1915)
E ShortcutService:   at com.android.server.pm.ShortcutPackage.saveToXml(ShortcutPackage.java:1788)
E ShortcutService:   at com.android.server.pm.ShortcutPackageItem.saveToFileLocked(ShortcutPackageItem.java:177)
E ShortcutService:   at com.android.server.pm.ShortcutPackageItem.saveShortcutPackageItem(ShortcutPackageItem.java:219)
```

### Mechanism

1. Chromium stores the icon as a string in the `ShortcutInfo` extras.
2. `PersistableBundle.saveToXml` writes strings as Modified UTF-8, whose length field is 16 bit — a hard limit of 65535 bytes.
3. At roughly 280 KB the field overflows and `writeUTF` throws.
4. The exception aborts writing `app.vanadium.browser.xml`, the file that holds **all** of the browser's shortcuts.

Three consequences that make this hard to catch, and that I think explain why the report has been hard to reproduce so far:

- **The encoded size matters, not the decoded bitmap.** A flat 512x512 PNG (3 KB) is harmless; a detailed 512x512 PNG (240 KB) is fatal. Both decode to the same 1 MiB bitmap. So "large icon" is not about pixel dimensions.
- **Nothing looks wrong while the device stays up.** The shortcut state is served from memory; only persistence fails. The damage is invisible until a reboot.
- **The boot log is clean.** There is no restore error, because there is nothing left to restore. Looking at logs after the reboot — the obvious thing to do — finds nothing.

### Test matrix

Each row changes one variable against the row above it. "Gone" means every PWA launcher entry of the browser disappeared, including PWAs installed months earlier and unrelated to the test.

| # | `maskable` | Icon | After reboot |
|---|---|---|---|
| 1 | yes | app logo, 44 KB / 207 KB | all PWAs gone |
| 2 | no | same logo files | all survive |
| 3 | yes, different app and origin | same logo files | all PWAs gone |
| 4 | yes | synthetic flat colour, 0.8 KB / 3.3 KB | all survive |
| 5 | yes | synthetic flat, transparent corners | all survive |
| 6 | yes | same logo pixels, re-encoded PNG | all PWAs gone |
| 7 | yes | synthetic colour noise, 34 KB / 240 KB | all PWAs gone |

Rows 2 and 4 together show that neither `maskable` alone nor the image files alone are sufficient — both conditions are needed. Row 3 rules out one specific app or origin. Row 5 rules out alpha transparency. Row 6 rules out PNG chunk structure and encoding (pixel-identical re-encode, still fatal). Row 7 reproduces the failure with an image that has no relationship to any real application.

### Minimal reproduction

Manifest:

```json
{
  "name": "Maskable Repro",
  "short_name": "Maskable Repro",
  "start_url": "/",
  "scope": "/",
  "display": "standalone",
  "icons": [
    { "src": "/icon-192.png", "sizes": "192x192", "type": "image/png", "purpose": "any" },
    { "src": "/icon-512.png", "sizes": "512x512", "type": "image/png", "purpose": "any" },
    { "src": "/icon-192.png", "sizes": "192x192", "type": "image/png", "purpose": "maskable" },
    { "src": "/icon-512.png", "sizes": "512x512", "type": "image/png", "purpose": "maskable" }
  ]
}
```

Icons — deterministic, Python standard library only, produces 33919 and 240252 byte PNGs:

```python
import zlib, struct, random

def chunk(tag, data):
    c = tag + data
    return struct.pack('>I', len(data)) + c + struct.pack('>I', zlib.crc32(c) & 0xffffffff)

def build(size, block=2, seed=12345):
    rnd = random.Random(seed)
    nb = (size + block - 1) // block
    blocks = [[(rnd.randrange(256), rnd.randrange(256), rnd.randrange(256))
               for _ in range(nb)] for _ in range(nb)]
    rows = bytearray()
    for y in range(size):
        rows.append(0)
        br = blocks[y // block]
        for x in range(size):
            r, g, b = br[x // block]
            rows.extend((r, g, b, 255))
    sig = bytes([137, 80, 78, 71, 13, 10, 26, 10])
    ihdr = struct.pack('>IIBBBBB', size, size, 8, 6, 0, 0, 0)
    return (sig + chunk(b'IHDR', ihdr)
            + chunk(b'IDAT', zlib.compress(bytes(rows), 9))
            + chunk(b'IEND', b''))

for s in (192, 512):
    open('icon-%d.png' % s, 'wb').write(build(s))
```

Steps:

1. Install one or more ordinary PWAs and confirm they survive a reboot.
2. Serve the manifest and the two icons over HTTPS, then install that PWA.
3. Reboot.
4. Every PWA launcher entry of the browser is gone.

To see the exception, run logcat while performing step 2: level `error`, buffers `main,system,crash`, no filter regex. The trace appears within a second or two of installing.

### Environment

- GrapheneOS, `google/komodo/komodo:17/CP2A.260805.005/2026081301:user/release-keys`
- Vanadium (`app.vanadium.browser`)

### Where this may belong

- **Chromium/Vanadium**: placing a string larger than 64 KB into `ShortcutInfo` extras exceeds a documented platform limit. This looks like the primary defect.
- **AOSP**: that one unserialisable shortcut aborts the entire package file, taking every other shortcut of that package with it, is an amplification that seems worth hardening independently of the caller's bug.

I have not narrowed the exact threshold. 3.3 KB survives, 34 KB fails.

### Workaround for affected users

Remove `"purpose": "maskable"` from the manifest, or replace the maskable icon with a flat, low-detail image that encodes to well under 64 KB. A maskable icon is supposed to be a full-bleed background with the motif inside the inner 40 % safe zone, which keeps it small anyway; the failures I saw all came from detailed logo artwork declared as maskable.

### Note on method

All seven test runs, the reboots and the logcat capture were performed by me on my own device — this is measured behaviour, not inferred. I used an AI assistant to design the test matrix, generate the synthetic test icons and draft this write-up.
