### ISSUE TITLE
eSIM activation fails from multiple carrier apps

### ISSUE THREAD

**Issue by jmvermeulen** [GrapheneOS/os_issue_tracker#3794]
Around a year ago I've setup a Pixel 6 with GrapheneOS and was able to activate the eSIM's for two providers just fine (KPN and simyo). Both provider do not support a QR-flow, you have to use their apps.

Now, with in a brand new Pixel 8 with a fresh GrapheneOS install I cannot activate eSIM's the same way anymore.
I've enabled 'eSIM  support' in the OS and DSCS is enabled too.

The logs are as the following:

```
07-25 11:08:02.010 20286 20391 D [nl.kpn.mijn.esim.EsimManager-downloadEsim]: will download eSIM 59-XXXX-XXXX from rsp.truphone.com
07-25 11:08:02.016 20286 20391 D [nl.kpn.mijn.esim.EsimManager-downloadEsim]: using activationCode 1$rsp.truphone.com$59-24CG9M-86SVOV
07-25 11:08:02.020 20286 20391 W PendingIntent: android.app.StackTrace: New mutable implicit PendingIntent: pkg=nl.kpn.mijn, action=download_subscription, featureId=null. This will be blocked once the app targets U+ for security reasons.
07-25 11:08:02.020 20286 20391 W PendingIntent:         at android.app.PendingIntent.checkPendingIntent2(PendingIntent.java:482)
07-25 11:08:02.020 20286 20391 W PendingIntent:         at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:771)
07-25 11:08:02.020 20286 20391 W PendingIntent:         at android.app.PendingIntent.getBroadcast(PendingIntent.java:758)
07-25 11:08:02.020 20286 20391 W PendingIntent:         at nl.kpn.mijn.esim.EsimManager.downloadEsim(Unknown Source:100)
07-25 11:08:02.020 20286 20391 W PendingIntent:         at nl.kpn.mijn.react.ESIMBridge.proceedEsimInstallation(Unknown Source:41)
07-25 11:08:02.020 20286 20391 W PendingIntent:         at nl.kpn.mijn.react.ESIMBridge.installESIM(Unknown Source:43)
07-25 11:08:02.020 20286 20391 W PendingIntent:         at java.lang.reflect.Method.invoke(Native Method)
07-25 11:08:02.020 20286 20391 W PendingIntent:         at com.facebook.react.bridge.JavaMethodWrapper.invoke(Unknown Source:148)
07-25 11:08:02.020 20286 20391 W PendingIntent:         at com.facebook.react.bridge.JavaModuleWrapper.invoke(Unknown Source:147)
07-25 11:08:02.020 20286 20391 W PendingIntent:         at com.facebook.jni.NativeRunnable.run(Native Method)
07-25 11:08:02.020 20286 20391 W PendingIntent:         at android.os.Handler.handleCallback(Handler.java:959)
07-25 11:08:02.020 20286 20391 W PendingIntent:         at android.os.Handler.dispatchMessage(Handler.java:100)
07-25 11:08:02.020 20286 20391 W PendingIntent:         at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source:0)
07-25 11:08:02.020 20286 20391 W PendingIntent:         at android.os.Looper.loopOnce(Looper.java:232)
07-25 11:08:02.020 20286 20391 W PendingIntent:         at android.os.Looper.loop(Looper.java:317)
07-25 11:08:02.020 20286 20391 W PendingIntent:         at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(Unknown Source:37)
07-25 11:08:02.020 20286 20391 W PendingIntent:         at java.lang.Thread.run(Thread.java:1012)
07-25 11:08:02.031  2289  2480 I EuiccController: isCompatChangeEnabled changeId: 224562872 changeEnabled: true
07-25 11:08:02.040  2289  2480 D EuiccController:  downloadSubscription cardId: 0 switchAfterDownload: true portIndex: 0 forceDeactivateSim: false callingPackage: nl.kpn.mijn isConsentNeededToResolvePortIndex: false shouldResolvePortIndex:true hasAdminPrivileges:false
07-25 11:08:02.043  2289  2480 I EuiccController: Caller can't manage subscription on target SIM or  User consent is required for resolving port index. Ask user's consent first
07-25 11:08:02.053 20286 20286 D [nl.kpn.mijn.esim.DownloadBroadcastReceiver-onReceive]: resultCode: 1, detailedCode: 0, action: download_subscription
07-25 11:08:02.053 20286 20286 D [nl.kpn.mijn.esim.DownloadBroadcastReceiver-onReceive]: Download resolvable error
07-25 11:08:02.053 20286 20286 W PendingIntent: android.app.StackTrace: New mutable implicit PendingIntent: pkg=nl.kpn.mijn, action=resolve_download_subscription, featureId=null. This will be blocked once the app targets U+ for security reasons.
07-25 11:08:02.053 20286 20286 W PendingIntent:         at android.app.PendingIntent.checkPendingIntent2(PendingIntent.java:482)
07-25 11:08:02.053 20286 20286 W PendingIntent:         at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:771)
07-25 11:08:02.053 20286 20286 W PendingIntent:         at android.app.PendingIntent.getBroadcast(PendingIntent.java:758)
07-25 11:08:02.053 20286 20286 W PendingIntent:         at nl.kpn.mijn.esim.DownloadBroadcastReceiver.resolveDownloadSubscriptionError(Unknown Source:20)
07-25 11:08:02.053 20286 20286 W PendingIntent:         at nl.kpn.mijn.esim.DownloadBroadcastReceiver.onReceive(Unknown Source:73)
07-25 11:08:02.053 20286 20286 W PendingIntent:         at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1810)
07-25 11:08:02.053 20286 20286 W PendingIntent:         at android.app.LoadedApk$ReceiverDispatcher$Args.$r8$lambda$mcNAAl1SQ4MyJPyDg8TJ2x2h0Rk(Unknown Source:0)
07-25 11:08:02.053 20286 20286 W PendingIntent:         at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
07-25 11:08:02.053 20286 20286 W PendingIntent:         at android.os.Handler.handleCallback(Handler.java:959)
07-25 11:08:02.053 20286 20286 W PendingIntent:         at android.os.Handler.dispatchMessage(Handler.java:100)
07-25 11:08:02.053 20286 20286 W PendingIntent:         at android.os.Looper.loopOnce(Looper.java:232)
07-25 11:08:02.053 20286 20286 W PendingIntent:         at android.os.Looper.loop(Looper.java:317)
07-25 11:08:02.053 20286 20286 W PendingIntent:         at android.app.ActivityThread.main(ActivityThread.java:8623)
07-25 11:08:02.053 20286 20286 W PendingIntent:         at java.lang.reflect.Method.invoke(Native Method)
07-25 11:08:02.053 20286 20286 W PendingIntent:         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
07-25 11:08:02.053 20286 20286 W PendingIntent:         at com.android.internal.os.ExecInit.main(ExecInit.java:50)
07-25 11:08:02.053 20286 20286 W PendingIntent:         at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
07-25 11:08:02.053 20286 20286 W PendingIntent:         at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
```

and 

```
07-25 10:22:23.825 12881 12881 E EuiccGoogle: [2] SwitchConfirmDialogActivity.onCreate: Calling package doesn't exist
07-25 10:22:23.825 12881 12881 E EuiccGoogle: com.google.android.flib.log.WhatATerribleException: android.content.pm.PackageManager$NameNotFoundException: nl.kpn.mijn
07-25 10:22:23.825 12881 12881 E EuiccGoogle:   at com.google.android.flib.log.Blog.wtf$ar$ds(PG:2)
07-25 10:22:23.825 12881 12881 E EuiccGoogle:   at com.google.android.euicc.logging.EuiccGoogleLog.wtf(PG:3)
07-25 10:22:23.825 12881 12881 E EuiccGoogle:   at com.android.euicc.ui.dialog.SwitchConfirmDialogActivity.onCreate(PG:25)
07-25 10:22:23.825 12881 12881 E EuiccGoogle:   at android.app.Activity.performCreate(Activity.java:9013)
07-25 10:22:23.825 12881 12881 E EuiccGoogle:   at android.app.Activity.performCreate(Activity.java:8991)
07-25 10:22:23.825 12881 12881 E EuiccGoogle:   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1531)
07-25 10:22:23.825 12881 12881 E EuiccGoogle:   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3986)
07-25 10:22:23.825 12881 12881 E EuiccGoogle:   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4184)
07-25 10:22:23.825 12881 12881 E EuiccGoogle:   at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:114)
07-25 10:22:23.825 12881 12881 E EuiccGoogle:   at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:231)
07-25 10:22:23.825 12881 12881 E EuiccGoogle:   at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:152)
07-25 10:22:23.825 12881 12881 E EuiccGoogle:   at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
07-25 10:22:23.825 12881 12881 E EuiccGoogle:   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2602)
07-25 10:22:23.825 12881 12881 E EuiccGoogle:   at android.os.Handler.dispatchMessage(Handler.java:107)
07-25 10:22:23.825 12881 12881 E EuiccGoogle:   at android.os.Looper.loopOnce(Looper.java:232)
07-25 10:22:23.825 12881 12881 E EuiccGoogle:   at android.os.Looper.loop(Looper.java:317)
07-25 10:22:23.825 12881 12881 E EuiccGoogle:   at android.app.ActivityThread.main(ActivityThread.java:8623)
07-25 10:22:23.825 12881 12881 E EuiccGoogle:   at java.lang.reflect.Method.invoke(Native Method)
07-25 10:22:23.825 12881 12881 E EuiccGoogle:   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
07-25 10:22:23.825 12881 12881 E EuiccGoogle:   at com.android.internal.os.ExecInit.main(ExecInit.java:50)
07-25 10:22:23.825 12881 12881 E EuiccGoogle:   at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
07-25 10:22:23.825 12881 12881 E EuiccGoogle:   at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
07-25 10:22:23.825 12881 12881 E EuiccGoogle: Caused by: android.content.pm.PackageManager$NameNotFoundException: nl.kpn.mijn
07-25 10:22:23.825 12881 12881 E EuiccGoogle:   at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:522)
07-25 10:22:23.825 12881 12881 E EuiccGoogle:   at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:505)
07-25 10:22:23.825 12881 12881 E EuiccGoogle:   at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:499)
07-25 10:22:23.825 12881 12881 E EuiccGoogle:   at com.android.euicc.ui.dialog.SwitchConfirmDialogActivity.onCreate(PG:20)
07-25 10:22:23.825 12881 12881 E EuiccGoogle:   ... 19 more
07-25 10:22:23.826 12881 12881 I EuiccGoogle: [2] SwitchConfirmDialogActivity.sendResultAndFinish: User confirmation confirmed: false itemPosition: -1
07-25 10:22:23.827  2289  2865 I EuiccController:  continueOperation portIndex: 0 usePortIndex: true
07-25 10:22:23.834 16802 16802 D [nl.kpn.mijn.esim.DownloadBroadcastReceiver-onReceive]: resultCode: 2, detailedCode: 0, action: resolve_download_subscription
```

For simyo I've only got the screenshots:

![image](https://github.com/user-attachments/assets/d8a42049-9ac9-40dc-ace8-aba430928f57)

![image](https://github.com/user-attachments/assets/a59bb7d5-beca-42c8-82d0-c57289ed17f6)

In the Android source-code I've found this:

`https://android.googlesource.com/platform/frameworks/opt/telephony/+/master/src/java/com/android/internal/telephony/euicc/EuiccController.java`

![image](https://github.com/user-attachments/assets/00e61c1e-a375-4295-a1bb-c5fcac11cb08)

There is *no consent* pop-up coming up in both apps, I'm not sure but this might be issue. 
I've two errors that indicate this:

`EuiccController: Caller can't manage subscription on target SIM or  User consent is required for resolving port index. Ask user's consent first`. 

And the 
`SwitchConfirmDialogActivity.onCreate: Calling package doesn't exist, tracing back to the SwitchConfirmDialogActivity`

**Comment by Rootflower** [comment]
Hello all, 
I'm new to GOS and I'm running it on a Pixel 9. I've installed 'Saily' app to obtain an eSIM but the installation fails both using the app installer and using the eSIM installer directly in the parameters of the phone. Is there anaything that has changed ? or is there something that I'm not correctly doing ? 
I've enabled 'eSIM support' in the OS and Sandboxed Google Play is running. 
Thank you
