### ISSUE TITLE
System_server crash

### ISSUE THREAD

**Issue by JD33** [GrapheneOS/os_issue_tracker#3954]
```
type: crash
SystemUptimeMs: 9884417
Process: system_server
Build: google/panther/panther:14/AP2A.240805.005/2024083100:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.pm.UserInfo.isManagedProfile()' on a null object reference
	at com.android.server.backup.BackupManagerService.enforcePermissionsOnUser(BackupManagerService.java:506)
	at com.android.server.backup.BackupManagerService.setBackupServiceActive(BackupManagerService.java:528)
	at com.android.server.backup.BackupManagerService$2.lambda$onReceive$0(BackupManagerService.java:183)
	at com.android.server.backup.BackupManagerService$2.$r8$lambda$kKECgvilRJBlBsX0mIMiprDkVmk(BackupManagerService.java:0)
	at com.android.server.backup.BackupManagerService$2$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)
```

**Comment by Zubbbz** [comment]
```
type: crash
osVersion: google/oriole/oriole:14/AP2A.240805.005.F1/2024083100:user/release-keys
uid: 1000 (u:r:system_server:s0)
cmdline: system_server
processUptime: 120815s

abortMessage: Splitting motion events requires a down time to be set for the target on connection 8151406 StatusBar (server) for MotionEvent

signal: 6 (SIGABRT), code -1 (SI_QUEUE)
threadName: InputDispatcher

backtrace:
    /apex/com.android.runtime/lib64/bionic/libc.so (abort+164, pc 64a24)
    /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+596, pc 905b24)
    /apex/com.android.art/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_0::__invoke(char const*)+80, pc 17ca0)
    /system/lib64/libbase.so (android::base::LogMessage::~LogMessage()+352, pc 171a0)
    /system/lib64/libinputflinger.so (android::inputdispatcher::InputDispatcher::prepareDispatchCycleLocked(long, std::__1::shared_ptr<android::inputdispatcher::Connection> const&, std::__1::shared_ptr<android::inputdispatcher::EventEntry const>, android::inputdispatcher::InputTarget const&)+2160, pc 1284e0)
    /system/lib64/libinputflinger.so (android::inputdispatcher::InputDispatcher::dispatchEventLocked(long, std::__1::shared_ptr<android::inputdispatcher::EventEntry const>, std::__1::vector<android::inputdispatcher::InputTarget, std::__1::allocator<android::inputdispatcher::InputTarget> > const&)+232, pc 122958)
    /system/lib64/libinputflinger.so (android::inputdispatcher::InputDispatcher::dispatchMotionLocked(long, std::__1::shared_ptr<android::inputdispatcher::MotionEntry const>, android::inputdispatcher::InputDispatcher::DropReason*, long&)+896, pc 11f920)
    /system/lib64/libinputflinger.so (android::inputdispatcher::InputDispatcher::dispatchOnceInnerLocked(long&)+1108, pc 11c3e4)
    /system/lib64/libinputflinger.so (android::inputdispatcher::InputDispatcher::dispatchOnce()+84, pc 11bee4)
    /system/lib64/libinputflinger_base.so (android::(anonymous namespace)::InputThreadImpl::threadLoop()+24, pc b338)
    /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+244, pc 115d4)
    /system/lib64/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*)+140, pc ed45c)
    /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204, pc 767ac)
    /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64, pc 67d50)
```

**Comment by coavins** [comment]
```
type: crash
SystemUptimeMs: 192087
Process: system_server
Build: google/bluejay/bluejay:14/AP2A.240905.003.F1/2024090400:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.RuntimeException: Failed to boot service com.android.server.policy.PermissionPolicyService: onBootPhase threw an exception during phase 550
	at com.android.server.SystemServiceManager.startBootPhase(SystemServiceManager.java:303)
	at com.android.server.SystemServer.lambda$startOtherServices$6(SystemServer.java:3042)
	at com.android.server.SystemServer.$r8$lambda$R8_YVQM1rsXoSgswlNNq9SsFhyw(SystemServer.java:0)
	at com.android.server.SystemServer$$ExternalSyntheticLambda9.run(R8$$SyntheticClass:0)
	at com.android.server.am.ActivityManagerService.systemReady(ActivityManagerService.java:8998)
	at com.android.server.SystemServer.startOtherServices(SystemServer.java:3039)
	at com.android.server.SystemServer.run(SystemServer.java:987)
	at com.android.server.SystemServer.main(SystemServer.java:702)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:872)
Caused by: java.lang.IllegalStateException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Error granting/upgrading runtime permissions for user 0
	at com.android.server.policy.PermissionPolicyService.grantOrUpgradeDefaultRuntimePermissionsIfNeeded(PermissionPolicyService.java:640)
	at com.android.server.policy.PermissionPolicyService.onStartUser(PermissionPolicyService.java:566)
	at com.android.server.policy.PermissionPolicyService.onBootPhase(PermissionPolicyService.java:436)
	at com.android.server.SystemServiceManager.startBootPhase(SystemServiceManager.java:300)
	... 10 more
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Error granting/upgrading runtime permissions for user 0
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:372)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2049)
	at com.android.server.policy.PermissionPolicyService.grantOrUpgradeDefaultRuntimePermissionsIfNeeded(PermissionPolicyService.java:638)
	... 13 more
Caused by: java.lang.IllegalStateException: Error granting/upgrading runtime permissions for user 0
	at com.android.server.policy.PermissionPolicyService.lambda$grantOrUpgradeDefaultRuntimePermissionsIfNeeded$0(PermissionPolicyService.java:633)
	at com.android.server.policy.PermissionPolicyService.$r8$lambda$7-qJ2Rz9W6aXjucp60KZxgKVPGU(PermissionPolicyService.java:0)
	at com.android.server.policy.PermissionPolicyService$$ExternalSyntheticLambda2.accept(R8$$SyntheticClass:0)
	at android.permission.PermissionControllerManager.lambda$grantOrUpgradeDefaultRuntimePermissions$24(PermissionControllerManager.java:698)
	at android.permission.PermissionControllerManager$$ExternalSyntheticLambda35.accept(D8$$SyntheticClass:0)
	at com.android.internal.infra.AndroidFuture.callListener(AndroidFuture.java:260)
	at com.android.internal.infra.AndroidFuture.lambda$callListenerAsync$1(AndroidFuture.java:247)
	at com.android.internal.infra.AndroidFuture$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)
```
