### ISSUE TITLE
Crash: Google Play Services crashed when trying to open Quick Share from the control panel (bluetooth off)

### ISSUE THREAD

**Issue by drunkbit** [GrapheneOS/os_issue_tracker#4062]
```
type: crash
osVersion: google/lynx/lynx:14/AP2A.240905.003/2024091900:user/release-keys
package: com.google.android.gms:243433038
process: com.google.android.gms.ui
processUptime: 373 + 243 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 138

java.lang.RuntimeException: Unable to resume activity {com.google.android.gms/com.google.android.gms.nearby.sharing.InternalReceiveSurfaceActivity}: java.lang.IllegalStateException: Unexpected implicit intent activity start : intent = Intent { act=android.bluetooth.adapter.action.REQUEST_DISCOVERABLE }
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5270)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5303)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:331)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:307)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleItem(TransactionExecutor.java:279)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:150)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2602)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: java.lang.IllegalStateException: Unexpected implicit intent activity start : intent = Intent { act=android.bluetooth.adapter.action.REQUEST_DISCOVERABLE }
	at aito.p(:com.google.android.gms@243433038@24.34.33 (190400-666809342):42)
	at aito.platform_startActivity(:com.google.android.gms@243433038@24.34.33 (190400-666809342):1)
	at oka.startActivity(:com.google.android.gms@243433038@24.34.33 (190400-666809342):1)
	at com.google.android.chimera.android.Activity.startActivity(:com.google.android.gms@243433038@24.34.33 (190400-666809342):1)
	at oka.public_startActivity(:com.google.android.gms@243433038@24.34.33 (190400-666809342):1)
	at okb.startActivity(:com.google.android.gms@243433038@24.34.33 (190400-666809342):1)
	at com.android.internal.gmscompat.util.GmcActivityUtils.handleNearbyShareActivityResume(GmcActivityUtils.java:94)
	at com.android.internal.gmscompat.util.GmcActivityUtils.onActivityResumed(GmcActivityUtils.java:48)
	at android.app.Application.dispatchActivityResumed(Application.java:437)
	at android.app.Activity.dispatchActivityResumed(Activity.java:1583)
	at android.app.Activity.onResume(Activity.java:2169)
	at okb.platform_onResume(:com.google.android.gms@243433038@24.34.33 (190400-666809342):1)
	at oka.onResume(:com.google.android.gms@243433038@24.34.33 (190400-666809342):3)
	at com.google.android.chimera.android.Activity.onResume(:com.google.android.gms@243433038@24.34.33 (190400-666809342):1)
	at opk.onResume(:com.google.android.gms@243433038@24.34.33 (190400-666809342):6)
	at com.google.android.gms.nearby.sharing.BaseCardActivity.onResume(:com.google.android.gms@243433038@24.34.33 (190400-666809342):1)
	at com.google.android.gms.nearby.sharing.ReceiveSurfaceChimeraActivity.onResume(:com.google.android.gms@243433038@24.34.33 (190400-666809342):1)
	at oka.public_onResume(:com.google.android.gms@243433038@24.34.33 (190400-666809342):1)
	at okb.onResume(:com.google.android.gms@243433038@24.34.33 (190400-666809342):5)
	at aito.onResume(:com.google.android.gms@243433038@24.34.33 (190400-666809342):9)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1727)
	at android.app.Activity.performResume(Activity.java:9171)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5260)
	... 16 more

```

**Comment by rajatgupta1998** [comment]
@thestinger could you please point out the commit(s) for the respective fix? I tried to skim through git, but couldn't find anything on the first look.
