### ISSUE TITLE
Settings crash after android 15 release

### ISSUE THREAD

**Issue by Lppsoeht** [GrapheneOS/os_issue_tracker#4140]
```
type: crash
osVersion: google/raven/raven:15/AP3A.241005.015/2024101600:user/release-keys
package: com.android.settings:35
process: com.android.settings
processUptime: 24548 + 296 ms

java.lang.IllegalStateException: Recording currently in progress - missing #endRecording() call?
	at android.graphics.RenderNode.beginRecording(RenderNode.java:484)
	at android.graphics.RenderNode.beginRecording(RenderNode.java:503)
	at androidx.compose.ui.graphics.layer.GraphicsLayerV29.record(GraphicsLayerV29.android.kt:225)
	at androidx.compose.ui.graphics.layer.GraphicsLayer.recordInternal(AndroidGraphicsLayer.android.kt:432)
	at androidx.compose.ui.graphics.layer.GraphicsLayer.record-mL-hObY(AndroidGraphicsLayer.android.kt:425)
	at androidx.compose.ui.platform.GraphicsLayerOwnerLayer.updateDisplayList(GraphicsLayerOwnerLayer.android.kt:237)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(AndroidComposeView.android.kt:1570)
	at android.view.View.draw(View.java:24845)
	at android.view.View.updateDisplayListIfDirty(View.java:23692)
	at android.view.View.draw(View.java:24573)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4537)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4298)
	at android.view.View.updateDisplayListIfDirty(View.java:23683)
	at android.view.View.draw(View.java:24573)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4537)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4298)
	at android.view.View.updateDisplayListIfDirty(View.java:23683)
	at android.view.View.draw(View.java:24573)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4537)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4298)
	at android.view.View.updateDisplayListIfDirty(View.java:23683)
	at android.view.View.draw(View.java:24573)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4537)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4298)
	at android.view.View.draw(View.java:24845)
	at com.android.internal.policy.DecorView.draw(DecorView.java:778)
	at android.view.View.updateDisplayListIfDirty(View.java:23692)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:694)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:700)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:798)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5659)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5312)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4303)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2917)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10324)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1406)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1015)
	at android.view.Choreographer.doFrame(Choreographer.java:945)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8736)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
```

**Comment by BlankEclair** [comment]
This is also reproducible even when other profiles are not involved
