### ISSUE TITLE
Android auto crash on Pixel 7a

### ISSUE THREAD

**Issue by Kudhoh** [GrapheneOS/os_issue_tracker#4249]
Hi, 
I've been having issues with android auto since i'm in holidays, randomly disconnecting and reconnecting or crashing.
I've seen similiar issues open these past days but I thought I should open an issue of my own.
I have a Pixel 7a. I never encountered this before. This seems to have begun since I changed country and the data is in roaming. As i'm not back yet, I can't confirm this. Not playing Spotify while driving seems to help.
Find the logs below. Build number is 2024102400.

```
type: crash
osVersion: google/lynx/lynx:15/AP3A.241005.015/2024102400:user/release-keys
package: com.google.android.projection.gearhead:127643424
process: com.google.android.projection.gearhead:car
processUptime: 5207476 + 396 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 145

java.lang.SecurityException: Access denied, requires: android.permission.MANAGE_USB
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3251)
	at android.os.Parcel.createException(Parcel.java:3235)
	at android.os.Parcel.readException(Parcel.java:3211)
	at android.os.Parcel.readException(Parcel.java:3153)
	at android.hardware.usb.IUsbManager$Stub$Proxy.getCurrentFunctions(IUsbManager.java:1528)
	at android.hardware.usb.UsbManager.getCurrentFunctions(UsbManager.java:1235)
	at iok.run(SourceFile:147)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8736)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
```

**Comment by Kudhoh** [comment]
> Are you using wired or wireless? Did you grant the required access for wired Android Auto in Settings > Apps > Sandboxed Google Play > Android Auto? That's a strange error if you have.

Hello,
I'm using wired mode. All the required permission are checked. I've been using my Pixel with Graphene since June I think, and it has been a flawless experience apart from this recent problem.

**Comment by Kudhoh** [comment]
I've just turned off and on again all the permissions required, just in case an update has introduced a bug. I have a 1 hour trip tomorrow, will see if this appears again.
