### ISSUE TITLE
crash: system_server

### ISSUE THREAD

**Issue by MichaelDevon** [GrapheneOS/os_issue_tracker#4347]
```
type: crash

SystemUptimeMs: 15640317
Process: system_server
Timestamp: 2024-11-17 06:47:27.902+0100
Build: google/shiba/shiba:15/AP3A.241105.007/2024110700:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.util.concurrent.TimeoutException: android.media.Ringtone.finalize() timed out after 10 seconds
	at android.media.MediaPlayer._release(Native Method)
	at android.media.MediaPlayer.release(MediaPlayer.java:2242)
	at android.media.Ringtone.finalize(Ringtone.java:657)
	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:370)
	at java.lang.Daemons$FinalizerDaemon.processReference(Daemons.java:350)
	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:322)
	at java.lang.Daemons$Daemon.run(Daemons.java:131)
	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by trombonekale** [comment]
Same here on Pixel 6a with build 2024110700

```
type: crash

SystemUptimeMs: 76705142
Process: system_server
Timestamp: 2024-11-17 14:00:46.165+0100
Build: google/bluejay/bluejay:15/AP3A.241105.007/2024110700:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
	at android.util.SparseArray.valueAt(SparseArray.java:346)
	at com.android.server.power.stats.PowerComponentAggregatedPowerStats.addPowerStats(PowerComponentAggregatedPowerStats.java:204)
	at com.android.server.power.stats.BinaryStatePowerStatsProcessor.flushPowerStats(BinaryStatePowerStatsProcessor.java:158)
	at com.android.server.power.stats.BinaryStatePowerStatsProcessor.start(BinaryStatePowerStatsProcessor.java:93)
	at com.android.server.power.stats.PowerStatsAggregator.start(PowerStatsAggregator.java:167)
	at com.android.server.power.stats.PowerStatsAggregator.aggregatePowerStats(PowerStatsAggregator.java:74)
	at com.android.server.power.stats.PowerStatsScheduler.aggregateAndStorePowerStats(PowerStatsScheduler.java:126)
	at com.android.server.power.stats.PowerStatsScheduler.$r8$lambda$GEaV9AQjfxC9uJ1Tfs7f2eF4_H0(PowerStatsScheduler.java:0)
	at com.android.server.power.stats.PowerStatsScheduler$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)
```

**Comment by Mickyh4rdy1990** [comment]
> ```
> type: crash
> 
> SystemUptimeMs: 15640317
> Process: system_server
> Timestamp: 2024-11-17 06:47:27.902+0100
> Build: google/shiba/shiba:15/AP3A.241105.007/2024110700:user/release-keys
> Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
> Loading-Progress: 1.0
> Dropped-Count: 0
> 
> java.util.concurrent.TimeoutException: android.media.Ringtone.finalize() timed out after 10 seconds
> 	at android.media.MediaPlayer._release(Native Method)
> 	at android.media.MediaPlayer.release(MediaPlayer.java:2242)
> 	at android.media.Ringtone.finalize(Ringtone.java:657)
> 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:370)
> 	at java.lang.Daemons$FinalizerDaemon.processReference(Daemons.java:350)
> 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:322)
> 	at java.lang.Daemons$Daemon.run(Daemons.java:131)
> 	at java.lang.Thread.run(Thread.java:1012)
> ```

**Comment by Mickyh4rdy1990** [comment]
```
type: crash
flags: dev options enabled

SystemUptimeMs: 5522842
Process: system_server
Timestamp: 2024-11-19 12:57:26.171+1100
Build: google/lynx/lynx:15/AP3A.241105.007/2024111800:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.AssertionError: java.lang.IllegalArgumentException: provider "network" does not exist
	at android.location.provider.LocationProviderBase$Service.lambda$setRequest$0(LocationProviderBase.java:336)
	at android.location.provider.LocationProviderBase$Service$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at com.android.server.SystemServer.run(SystemServer.java:983)
	at com.android.server.SystemServer.main(SystemServer.java:661)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:880)
Caused by: java.lang.IllegalArgumentException: provider "network" does not exist
	at com.android.internal.util.Preconditions.checkArgument(Preconditions.java:64)
	at com.android.server.location.LocationManagerService.registerLocationListener(LocationManagerService.java:845)
	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:1618)
	at com.android.location.fused.FusedLocationProvider$ChildLocationListener.resetProviderRequest(FusedLocationProvider.java:304)
	at com.android.location.fused.FusedLocationProvider$ChildLocationListener.-$$Nest$mresetProviderRequest(FusedLocationProvider.java:0)
	at com.android.location.fused.FusedLocationProvider.updateRequirementsLocked(FusedLocationProvider.java:173)
	at com.android.location.fused.FusedLocationProvider.onSetRequest(FusedLocationProvider.java:123)
	at android.location.provider.LocationProviderBase$Service.setRequest(LocationProviderBase.java:331)
	at com.android.server.location.provider.proxy.ProxyLocationProvider.lambda$onSetRequest$0(ProxyLocationProvider.java:184)
	at com.android.server.location.provider.proxy.ProxyLocationProvider.$r8$lambda$7VMdFID5UKJaFx-7qHYncL9kLJk(ProxyLocationProvider.java:0)
	at com.android.server.location.provider.proxy.ProxyLocationProvider$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:0)
	at com.android.server.servicewatcher.ServiceWatcherImpl$MyServiceConnection.runOnBinder(ServiceWatcherImpl.java:257)
	at com.android.server.servicewatcher.ServiceWatcherImpl.lambda$runOnBinder$0(ServiceWatcherImpl.java:126)
	at com.android.server.servicewatcher.ServiceWatcherImpl.$r8$lambda$GCGDYqQZRK7jCQUNZnY8QjXgR2Y(ServiceWatcherImpl.java:0)
	at com.android.server.servicewatcher.ServiceWatcherImpl$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

**Comment by Mickyh4rdy1990** [comment]
Yes I am

**Comment by muhomorr** [comment]
@Mickyh4rdy1990 What was happening at the time of the crash? Is this crash reproducible?

**Comment by minhng99** [comment]
same crash as @Mickyh4rdy1990
I am using a GPS mock location app but it was not active at the time of the crash, the phone wasn't doing anything in particular and just sleeping, I saw it "rebooting" by itself and this crash appeared.
I said "reboot" but I don't think that was the case because my SIM PIN wasn't triggered.

```
type: crash
flags: dev options enabled

SystemUptimeMs: 47126732
Process: system_server
Timestamp: 2024-11-22 10:34:03.346+0700
Build: google/husky/husky:15/AP3A.241105.007/2024111800:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.AssertionError: java.lang.IllegalArgumentException: provider "network" does not exist
	at android.location.provider.LocationProviderBase$Service.lambda$setRequest$0(LocationProviderBase.java:336)
	at android.location.provider.LocationProviderBase$Service$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at com.android.server.SystemServer.run(SystemServer.java:983)
	at com.android.server.SystemServer.main(SystemServer.java:661)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:880)
Caused by: java.lang.IllegalArgumentException: provider "network" does not exist
	at com.android.internal.util.Preconditions.checkArgument(Preconditions.java:64)
	at com.android.server.location.LocationManagerService.registerLocationListener(LocationManagerService.java:845)
	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:1618)
	at com.android.location.fused.FusedLocationProvider$ChildLocationListener.resetProviderRequest(FusedLocationProvider.java:304)
	at com.android.location.fused.FusedLocationProvider$ChildLocationListener.-$$Nest$mresetProviderRequest(FusedLocationProvider.java:0)
	at com.android.location.fused.FusedLocationProvider.updateRequirementsLocked(FusedLocationProvider.java:173)
	at com.android.location.fused.FusedLocationProvider.onSetRequest(FusedLocationProvider.java:123)
	at android.location.provider.LocationProviderBase$Service.setRequest(LocationProviderBase.java:331)
	at com.android.server.location.provider.proxy.ProxyLocationProvider.lambda$onSetRequest$0(ProxyLocationProvider.java:184)
	at com.android.server.location.provider.proxy.ProxyLocationProvider.$r8$lambda$7VMdFID5UKJaFx-7qHYncL9kLJk(ProxyLocationProvider.java:0)
	at com.android.server.location.provider.proxy.ProxyLocationProvider$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:0)
	at com.android.server.servicewatcher.ServiceWatcherImpl$MyServiceConnection.runOnBinder(ServiceWatcherImpl.java:257)
	at com.android.server.servicewatcher.ServiceWatcherImpl.lambda$runOnBinder$0(ServiceWatcherImpl.java:126)
	at com.android.server.servicewatcher.ServiceWatcherImpl.$r8$lambda$GCGDYqQZRK7jCQUNZnY8QjXgR2Y(ServiceWatcherImpl.java:0)
	at com.android.server.servicewatcher.ServiceWatcherImpl$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

**Comment by trombonekale** [comment]
type: crash

SystemUptimeMs: 5259231
Process: system_server
Timestamp: 2024-12-02 23:09:11.444+0100
Build: google/bluejay/bluejay:15/AP3A.241105.007/2024112700:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
	at android.util.SparseArray.valueAt(SparseArray.java:346)
	at com.android.server.power.stats.PowerComponentAggregatedPowerStats.addPowerStats(PowerComponentAggregatedPowerStats.java:204)
	at com.android.server.power.stats.BinaryStatePowerStatsProcessor.flushPowerStats(BinaryStatePowerStatsProcessor.java:158)
	at com.android.server.power.stats.BinaryStatePowerStatsProcessor.start(BinaryStatePowerStatsProcessor.java:93)
	at com.android.server.power.stats.PowerStatsAggregator.start(PowerStatsAggregator.java:167)
	at com.android.server.power.stats.PowerStatsAggregator.aggregatePowerStats(PowerStatsAggregator.java:74)
	at com.android.server.power.stats.PowerStatsScheduler.aggregateAndStorePowerStats(PowerStatsScheduler.java:126)
	at com.android.server.power.stats.PowerStatsScheduler.$r8$lambda$GEaV9AQjfxC9uJ1Tfs7f2eF4_H0(PowerStatsScheduler.java:0)
	at com.android.server.power.stats.PowerStatsScheduler$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)
