### ISSUE TITLE
Google Weather crashes

### ISSUE THREAD

**Issue by F1VWdk** [GrapheneOS/os_issue_tracker#4369]
Google Weather app crashes, log below. After installing Google Weather and adding locations, opening detail view of any of them crashes the app:
```

type: crash
osVersion: google/komodo/komodo:15/AP3A.241105.008/2024111800:user/release-keys
package: com.google.android.apps.weather:10003254, targetSdk 35
process: com.google.android.apps.weather
processUptime: 339 + 206 ms
installer: com.android.vending

com.google.apps.tiktok.e.a.c: A LocalSubscriptionCallbacks didn't handle an error. It must either catch the error and pass it as part of onLoaded(), or register an error handler in onLoadError().
	at com.google.android.material.f.a.S(PG:3)
	at com.google.android.apps.weather.o.f.e.a(PG:1)
	at com.google.apps.tiktok.e.a.l.a(PG:21)
	at com.google.apps.tiktok.e.a.r.a(PG:72)
	at com.google.android.material.snackbar.e.run(PG:300)
	at f.a.dw.run(PG:27)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at com.google.b.r.a.cp.a(PG:3)
	at com.google.b.r.a.bu.run(PG:19)
	at com.google.b.r.a.cq.run(PG:5)
	at com.google.b.r.a.ch.run(PG:85)
	at f.a.dw.run(PG:27)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at com.google.b.r.a.cp.a(PG:3)
	at com.google.b.r.a.bu.run(PG:19)
	at com.google.b.r.a.cq.run(PG:5)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8744)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: java.lang.SecurityException: Settings key: <media_vibration_intensity> is not readable. From S+, settings keys annotated with @hide are restricted to system_server and system apps only, unless they are annotated with @Readable.
	at android.provider.Settings$NameValueCache.getStringForUser(Settings.java:3560)
	at android.provider.Settings$System.getStringForUser(Settings.java:4240)
	at android.provider.Settings$System.getIntForUser(Settings.java:4425)
	at android.provider.Settings$System.getInt(Settings.java:4419)
	at com.google.android.apps.weather.nowcastandinsights.b.a.f.an(PG:23)
	at com.google.android.apps.weather.g.b.b.e.c(PG:98)
	at com.google.android.apps.weather.g.b.b.c.bc(PG:12)
	at i.b.b.a.a.bG(PG:11)
	at kotlinx.coroutines.am.run(PG:114)
	at com.google.apps.tiktok.b.f.run(PG:601)
	at com.google.android.libraries.b.q.run(PG:3)
	at com.google.b.l.b.b.run(PG:50)
	at androidx.work.impl.utils.a.run(PG:46)
	at java.lang.Thread.run(Thread.java:1012)
	at com.google.android.libraries.b.c.b.run(PG:64)

```

**Comment by DifferentWaste** [comment]
P9P XL
Build number 2024112700
Only noticed issue appearing after last stable update

```
type: crash
osVersion: google/komodo/komodo:15/AP3A.241105.008/2024112700:user/release-keys
package: com.google.android.apps.weather:10003254, targetSdk 35
process: com.google.android.apps.weather
processUptime: 87730 + 217 ms
installer: com.android.vending

com.google.apps.tiktok.e.a.c: A LocalSubscriptionCallbacks didn't handle an error. It must either catch the error and pass it as part of onLoaded(), or register an error handler in onLoadError().
	at com.google.android.material.f.a.S(PG:3)
	at com.google.android.apps.weather.o.f.e.a(PG:1)
	at com.google.apps.tiktok.e.a.l.a(PG:21)
	at com.google.apps.tiktok.e.a.r.a(PG:72)
	at com.google.android.material.snackbar.e.run(PG:300)
	at f.a.dw.run(PG:27)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at com.google.b.r.a.cp.a(PG:3)
	at com.google.b.r.a.bu.run(PG:19)
	at com.google.b.r.a.cq.run(PG:5)
	at com.google.b.r.a.ch.run(PG:85)
	at f.a.dw.run(PG:27)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at com.google.b.r.a.cp.a(PG:3)
	at com.google.b.r.a.bu.run(PG:19)
	at com.google.b.r.a.cq.run(PG:5)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8744)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: java.lang.SecurityException: Settings key: <media_vibration_intensity> is not readable. From S+, settings keys annotated with @hide are restricted to system_server and system apps only, unless they are annotated with @Readable.
	at android.provider.Settings$NameValueCache.getStringForUser(Settings.java:3560)
	at android.provider.Settings$System.getStringForUser(Settings.java:4240)
	at android.provider.Settings$System.getIntForUser(Settings.java:4425)
	at android.provider.Settings$System.getInt(Settings.java:4419)
	at com.google.android.apps.weather.nowcastandinsights.b.a.f.an(PG:23)
	at com.google.android.apps.weather.g.b.b.e.c(PG:98)
	at com.google.android.apps.weather.g.b.b.c.bc(PG:12)
	at i.b.b.a.a.bG(PG:11)
	at kotlinx.coroutines.am.run(PG:114)
	at com.google.apps.tiktok.b.f.run(PG:601)
	at com.google.android.libraries.b.q.run(PG:3)
	at com.google.b.l.b.b.run(PG:50)
	at androidx.work.impl.utils.a.run(PG:46)
	at java.lang.Thread.run(Thread.java:1012)
	at com.google.android.libraries.b.c.b.run(PG:64)
```
