### ISSUE TITLE
Google Phone crashes when any of AI features enabled

### ISSUE THREAD

**Issue by F1VWdk** [GrapheneOS/os_issue_tracker#4370]
Google Phone app crashes when, I think, any of "ASSISTIVE" features (Scam Detection, Hold for Me, Direct My Call, Call Screen, or Call Notes) are enabled. Enabling Caller ID & spam appears NOT to crash the app. I tried with AICore & Private Compute Services and without.
```

type: crash
osVersion: google/komodo/komodo:15/AP3A.241105.008/2024111800:user/release-keys
package: com.google.android.dialer:18101818, targetSdk 35
process: com.google.android.dialer
processUptime: 3101 + 398 ms
installer: com.android.vending

zvk: 
	at tk_trace.NoAccountWorkerFactory startWork()(Unknown Source:0)
	at tk_trace.com.android.dialer.voicemail.service.impl.VvmTaskWorker startWork()(Unknown Source:0)
	at tk_trace.com.android.dialer.voicemail.service.impl.VvmTaskWorker startWork()(Unknown Source:0)
	at tk_trace.WorkManager:TikTokListenableWorker startWork(Unknown Source:0)
Caused by: java.lang.SecurityException: ConnectivityService: user 10166 has no permission to access restricted network.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3251)
	at android.os.Parcel.createException(Parcel.java:3235)
	at android.os.Parcel.readException(Parcel.java:3211)
	at android.os.Parcel.readException(Parcel.java:3153)
	at android.net.IConnectivityManager$Stub$Proxy.requestNetwork(IConnectivityManager.java:2450)
	at android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4624)
	at android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4657)
	at android.net.ConnectivityManager.requestNetwork(ConnectivityManager.java:4829)
	at dd$$ExternalSyntheticApiModelOutline2.m(D8$$SyntheticClass:68)
	at qsz.call(PG:1728)
	at zji.a(PG:8)
	at abcc.a(PG:175)
	at abes.a(PG:3)
	at abdv.run(PG:19)
	at abeu.run(PG:5)
	at abek.run(PG:219)
	at vgp.run(PG:3)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at ukc.run(PG:163)
	at uvi.run(PG:616)
	at java.lang.Thread.run(Thread.java:1012)
	at vht.run(PG:64)

```

**Comment by xNul** [comment]
I have this issue too and others as well.

https://discuss.grapheneos.org/d/17030-google-phone-app-crashing-dialer
https://discuss.grapheneos.org/d/16283-google-phone-app-keeps-crashing
https://discuss.grapheneos.org/d/17519-google-dialer-and-weather-started-to-crash
