### ISSUE TITLE
Error in google play services

### ISSUE THREAD

**Issue by JSShnhltz** [GrapheneOS/os_issue_tracker#4391]
```
type: crash
osVersion: google/oriole/oriole:15/AP3A.241105.007/2024111800:user/release-keys
package: com.google.android.gms:240513038, targetSdk 34
sharedUid: com.google.uid.shared
process: com.google.android.gms.persistent
processUptime: 140 + 342 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 150

java.lang.RuntimeException: Unable to instantiate application co.g.App package com.google.android.gms: java.lang.RuntimeException: Unable to get provider com.google.android.gms.gservices.provider.GservicesProvider: java.lang.NullPointerException
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1480)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1405)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7503)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2425)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8744)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: java.lang.RuntimeException: Unable to get provider com.google.android.gms.gservices.provider.GservicesProvider: java.lang.NullPointerException
	at android.app.ActivityThread.installProvider(ActivityThread.java:8336)
	at android.app.ActivityThread.acquireProvider(ActivityThread.java:7922)
	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:3905)
	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2574)
	at android.content.ContentResolver.query(ContentResolver.java:1219)
	at android.content.ContentResolver.query(ContentResolver.java:1167)
	at android.content.ContentResolver.query(ContentResolver.java:1123)
	at dies.d(:com.google.android.gms@240513038@24.05.13 (190400-602827846):8)
	at diew.c(:com.google.android.gms@240513038@24.05.13 (190400-602827846):5)
	at diem.j(:com.google.android.gms@240513038@24.05.13 (190400-602827846):206)
	at com.google.android.gms.common.app.GmsApplication.attachBaseContext(:com.google.android.gms@240513038@24.05.13 (190400-602827846):382)
	at android.app.Application.attach(Application.java:352)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1363)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1473)
	... 13 more
Caused by: java.lang.NullPointerException
	at eecd.y(:com.google.android.gms@240513038@24.05.13 (190400-602827846):5)
	at oig.a(:com.google.android.gms@240513038@24.05.13 (190400-602827846):3)
	at ohs.<init>(:com.google.android.gms@240513038@24.05.13 (190400-602827846):4)
	at oit.<init>(:com.google.android.gms@240513038@24.05.13 (190400-602827846):3)
	at oit.f(:com.google.android.gms@240513038@24.05.13 (190400-602827846):14)
	at com.google.android.gms.chimera.GmsAppComponentFactory.a(:com.google.android.gms@240513038@24.05.13 (190400-602827846):1)
	at com.google.android.gms.chimera.GmsAppComponentFactory.instantiateProvider(:com.google.android.gms@240513038@24.05.13 (190400-602827846):125)
	at android.app.ActivityThread.installProvider(ActivityThread.java:8320)
	... 26 more
```

**Comment by muhomorr** [comment]
You are running a very old Play services version. Update Play services through the App Store or Play Store.
