### ISSUE TITLE
Google play service crash when enabling nfc from webauthn fido2 popup prompt

### ISSUE THREAD

**Issue by ghost** [GrapheneOS/os_issue_tracker#4449]
```
type: crash
osVersion: google/panther/panther:15/AP3A.241105.007/2024120400:user/release-keys
package: com.google.android.gms:244433035, targetSdk 35
process: com.google.android.gms.ui
processUptime: 25693 + 222 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 151

java.lang.RuntimeException: Error receiving broadcast Intent { act=android.nfc.action.ADAPTER_STATE_CHANGED flg=0x4000010 (has extras) } in com.google.android.gms.fido.u2f.api.controller.NfcBroadcastReceiver@2219583
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1827)
	at android.app.LoadedApk$ReceiverDispatcher$Args.$r8$lambda$mcNAAl1SQ4MyJPyDg8TJ2x2h0Rk(Unknown Source:0)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8744)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at fl.aE(:com.google.android.gms@244433035@24.44.33 (260400-694629214):12)
	at fl.N(:com.google.android.gms@244433035@24.44.33 (260400-694629214):27)
	at ca.c(:com.google.android.gms@244433035@24.44.33 (260400-694629214):58)
	at ca.a(:com.google.android.gms@244433035@24.44.33 (260400-694629214):3)
	at de.ie(:com.google.android.gms@244433035@24.44.33 (260400-694629214):110)
	at de.dismiss(:com.google.android.gms@244433035@24.44.33 (260400-694629214):2)
	at erca.dismiss(:com.google.android.gms@244433035@24.44.33 (260400-694629214):8)
	at awky.s(:com.google.android.gms@244433035@24.44.33 (260400-694629214):51)
	at awky.k(:com.google.android.gms@244433035@24.44.33 (260400-694629214):81)
	at axvf.b(:com.google.android.gms@244433035@24.44.33 (260400-694629214):499)
	at awky.r(:com.google.android.gms@244433035@24.44.33 (260400-694629214):10)
	at axcv.f(:com.google.android.gms@244433035@24.44.33 (260400-694629214):5)
	at awse.b(:com.google.android.gms@244433035@24.44.33 (260400-694629214):9)
	at axtm.c(:com.google.android.gms@244433035@24.44.33 (260400-694629214):72)
	at axtm.b(:com.google.android.gms@244433035@24.44.33 (260400-694629214):104)
	at com.google.android.gms.fido.u2f.api.controller.NfcBroadcastReceiver.ku(:com.google.android.gms@244433035@24.44.33 (260400-694629214):105)
	at com.google.android.gms.libs.punchclock.tracing.TracingBroadcastReceiver.onReceive(:com.google.android.gms@244433035@24.44.33 (260400-694629214):17)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1819)
	... 12 more
```

**Comment by zoechalfant** [comment]
I am also having this problem trying to use 2fac yubikey either as NFC or as USB.

**Comment by empratyush** [comment]
unable to reproduce this.
