### ISSUE TITLE
Android auto crashes repeatedly

### ISSUE THREAD

**Issue by YussefR** [GrapheneOS/os_issue_tracker#4525]
While playing audio on substack and running maps on android auto, the car screen turns black and gets stuck till I disconnect my phone and connect it again. Not a car or phone issue. 

```
type: crash
osVersion: google/husky/husky:15/AP4A.241205.013/2024121200:user/release-keys
package: com.google.android.projection.gearhead:132644464, targetSdk 35
sharedUid: com.google.android.projection.gearhead
process: com.google.android.projection.gearhead:projection
processUptime: 19740 + 572 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 152

java.lang.OutOfMemoryError: Failed to allocate a 296 byte allocation with 1179584 free bytes and 1151KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at qgj.f(SourceFile:1)
	at met.b(SourceFile:14)
	at kfg.cE(SourceFile:205)
	at dwn.a(SourceFile:29)
	at dwn.g(SourceFile:42)
	at dwn.m(SourceFile:16)
	at lhx.m(SourceFile:1)
	at lhy.m(SourceFile:66)
	at puq.run(SourceFile:527)
	at android.os.Handler.handleCallback(Handler.java:991)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8826)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
```

**Comment by LinuxLover9** [comment]
I have also repeated crashes. Reinstalled to make sure I have the latest version, but still crashed within an hour of usage.

**Comment by LinuxLover9** [comment]
```
type: crash
osVersion: google/panther/panther:15/AP3A.241105.007/2024120400:user/release-keys
userType: full.secondary
flags: dev options enabled
package: com.google.android.projection.gearhead:133644654, targetSdk 35
sharedUid: com.google.android.projection.gearhead
process: com.google.android.projection.gearhead:projection
processUptime: 1407 + 545 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 152

irw: Car not connected when trying to register CarDisplayLayoutUpdateCompleteListener
	at iqe.j(SourceFile:56)
	at iqe.e(SourceFile:13)
	at mpy.dw(SourceFile:22)
	at lmo.dw(SourceFile:86)
	at jvo.a(SourceFile:57)
	at vmd.c(SourceFile:18)
	at jvp.k(SourceFile:19)
	at jvm.a(SourceFile:20)
	at irt.v(SourceFile:179)
	at jay.a(SourceFile:957)
	at pnz.f(SourceFile:19)
	at pwg.run(SourceFile:592)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8744)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: qeg: java.lang.IllegalStateException: OutOfCarLifecycle
	at qhk.j(SourceFile:115)
	at qhk.i(SourceFile:1)
	at qcx.p(SourceFile:19)
	at qcx.o(SourceFile:8)
	at jlp.a(SourceFile:336)
	at isc.a(SourceFile:255)
	at iqe.j(SourceFile:1)
	... 21 more
Caused by: java.lang.IllegalStateException: OutOfCarLifecycle
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3259)
	at android.os.Parcel.createException(Parcel.java:3235)
	at android.os.Parcel.readException(Parcel.java:3211)
	at android.os.Parcel.readException(Parcel.java:3153)
	at gpz.ef(SourceFile:11)
	at ppm.aE(SourceFile:10)
	at qie.b(SourceFile:83)
	at pxg.a(SourceFile:205)
	at pmg.d(SourceFile:16)
	at pxf.a(SourceFile:291)
	at qcx.o(SourceFile:1)
	... 24 more
```

**Comment by xelayz** [comment]
My Android Auto is also always crashing. So maybe there is one big problem which cause all the crashs. I tried 3 different cables.

```
type: crash
osVersion: google/shiba/shiba:15/AP4A.241205.013/2024121200:user/release-keys
flags: dev options enabled
package: com.google.android.projection.gearhead:133644654, targetSdk 35
sharedUid: com.google.android.projection.gearhead
process: com.google.android.projection.gearhead:projection
processUptime: 4479 + 848 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 152

irw: Unable to access car
	at iqe.j(SourceFile:56)
	at iqe.e(SourceFile:13)
	at jlx.dw(SourceFile:32)
	at jvo.a(SourceFile:57)
	at vmd.c(SourceFile:18)
	at jvp.k(SourceFile:19)
	at jvm.a(SourceFile:20)
	at irt.v(SourceFile:179)
	at jay.a(SourceFile:957)
	at pnz.f(SourceFile:19)
	at pwg.run(SourceFile:592)
	at android.os.Handler.handleCallback(Handler.java:991)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8826)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: qeg: java.lang.IllegalStateException: OutOfCarLifecycle
	at qhk.j(SourceFile:115)
	at qhk.i(SourceFile:1)
	at qcx.p(SourceFile:19)
	at qcx.j(SourceFile:9)
	at pxs.x(SourceFile:10)
	at njk.x(SourceFile:5)
	at ozh.g(SourceFile:1)
	at jlp.a(SourceFile:1026)
	at isc.a(SourceFile:255)
	at iqe.j(SourceFile:1)
	... 20 more
Caused by: java.lang.IllegalStateException: OutOfCarLifecycle
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3248)
	at android.os.Parcel.createException(Parcel.java:3224)
	at android.os.Parcel.readException(Parcel.java:3200)
	at android.os.Parcel.readException(Parcel.java:3142)
	at gpz.ee(SourceFile:11)
	at ppm.A(SourceFile:7)
	at pxd.a(SourceFile:206)
	at qcx.a(SourceFile:14)
	at pxc.call(SourceFile:232)
	at qcx.j(SourceFile:1)
	... 26 more
```

**Comment by Paolo5466** [comment]
```
type: crash
osVersion: google/panther/panther:15/AP4A.241205.013/2024123000:user/release-keys
flags: dev options enabled
package: com.google.android.projection.gearhead:133644654, targetSdk 35
sharedUid: com.google.android.projection.gearhead
process: com.google.android.projection.gearhead:projection
processUptime: 20252 + 505 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 152

java.lang.RuntimeException: Unable to create service com.google.android.gearhead.appdecor.AppDecorService: irw: Unable to register for car sensor updates
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5093)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2505)
	at android.os.Handler.dispatchMessage(Handler.java:109)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8826)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: irw: Unable to register for car sensor updates
	at iqe.j(SourceFile:56)
	at iqe.e(SourceFile:13)
	at ozq.a(SourceFile:29)
	at irt.x(SourceFile:115)
	at com.google.android.gearhead.appdecor.AppDecorService.onCreate(SourceFile:42)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5080)
	... 11 more
Caused by: qeg: java.lang.IllegalStateException: OutOfCarLifecycle
	at qhk.j(SourceFile:115)
	at qhk.i(SourceFile:1)
	at qhr.d(SourceFile:10)
	at com.google.android.gearhead.appdecor.AppDecorService.a(SourceFile:3)
	at lck.a(SourceFile:84)
	at isc.a(SourceFile:255)
	at iqe.j(SourceFile:1)
	... 16 more
Caused by: java.lang.IllegalStateException: OutOfCarLifecycle
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3248)
	at android.os.Parcel.createException(Parcel.java:3224)
	at android.os.Parcel.readException(Parcel.java:3200)
	at android.os.Parcel.readException(Parcel.java:3142)
	at gpz.ee(SourceFile:11)
	at pte.s(SourceFile:6)
	at qhr.d(SourceFile:4)
	... 20 more
```

**Comment by Paolo5466** [comment]
> @Paolo5466 That's a USB or wireless connectivity issue you need to resolve. Use a better cable and clean the ports with something that's not hard and won't make it worse leaving more dust.

Thanks, I'll try changing the cable

Have a great day

**Comment by Paolo5466** [comment]
Hi
Actually is still happening with a new cable too.
Happens with Android Auto wireless also.

I notice that when this happens tje phone is unusually warm

**Comment by alakbarz** [comment]
+1 happens on both wired and wireless Android Auto.

Steps to reproduce:
- Run Android Auto for about an hour or so.
- Android Auto crashes and doesn't reconnect until about 30 seconds to a minute later.
- Shortly after (5 minutes or less) crashes again.
- Repeats until phone is restarted.

My phone is usually warm (not due to placement in vehicle).

Looking at running services in developer options shows RAM is almost full every time. Restart is the only fix.

Strong gut feeling there's a memory leak somewhere.

This behaviour has been persistent across multiple Android Auto updates through the GrapheneOS app store.

**Comment by nathansgithub** [comment]
I wanted to say that I'm seeing this OutOfMemoryError error pretty regularly (but not all the time), on the stable release channel. It's accompanied by the music display disappearing and restarting over and over again. The music itself doesn't stop playing.

``````
type: crash
osVersion: google/akita/akita:15/BP1A.250405.007.B1/2025042500:user/release-keys
flags: dev options enabled
package: com.google.android.projection.gearhead:140651234, targetSdk 36
sharedUid: com.google.android.projection.gearhead
process: com.google.android.projection.gearhead:projection
processUptime: 56175 + 455 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 156

java.lang.OutOfMemoryError: Failed to allocate a 40 byte allocation with 2341104 free bytes and 2286KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at android.os.Parcel.createFloatArray(Parcel.java:1884)
	at neg.createFromParcel(SourceFile:359)
	at fra.a(SourceFile:9)
	at nnl.ej(SourceFile:6)
	at fqz.onTransact(SourceFile:21)
	at android.os.Binder.execTransactInternal(Binder.java:1455)
	at android.os.Binder.execTransact(Binder.java:1389)
```

**Comment by nathansgithub** [comment]
Thank you. I did that and haven't seen that issue since then. It's a sporadic bug, so it's hard to say it's stopped happening, but it looks good so far.
